EVRTOSProject: Core/Src/adc.c File Reference
adc.c File Reference
This file provides code for the configuration of the ADC instances.
#include "adc.h"
Functions
void MX_ADC1_Init (void)
void MX_ADC2_Init (void)
void HAL_ADC_MspInit (ADC_HandleTypeDef *adcHandle)
void HAL_ADC_MspDeInit (ADC_HandleTypeDef *adcHandle)
Variables
ADC_HandleTypeDef hadc1
ADC_HandleTypeDef hadc2
DMA_HandleTypeDef hdma_adc1
Detailed Description
This file provides code for the configuration of the ADC instances.
Attention
Copyright (c) 2023 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file adc.c.
Function Documentation
HAL_ADC_MspDeInit()
void HAL_ADC_MspDeInit (ADC_HandleTypeDef * adcHandle)
ADC1 GPIO Configuration PA1 ---—> ADC1_IN1 PA2 ---—> ADC1_IN2 PA3 ---—> ADC1_IN3 PA4 ---—> ADC1_IN4
ADC2 GPIO Configuration PA5 ---—> ADC2_IN5 PA6 ---—> ADC2_IN6
Definition at line 236 of file adc.c.
HAL_ADC_MspInit()
void HAL_ADC_MspInit (ADC_HandleTypeDef * adcHandle)
ADC1 GPIO Configuration PA1 ---—> ADC1_IN1 PA2 ---—> ADC1_IN2 PA3 ---—> ADC1_IN3 PA4 ---—> ADC1_IN4
ADC2 GPIO Configuration PA5 ---—> ADC2_IN5 PA6 ---—> ADC2_IN6
Definition at line 165 of file adc.c.
References Error_Handler(), and hdma_adc1.
MX_ADC1_Init()
void MX_ADC1_Init (void)
Configure the global features of the ADC (Clock, Resolution, Data Alignment and number of conversion)
Configure the analog watchdog
Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time.
Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time.
Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time.
Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time.
Definition at line 32 of file adc.c.
References Error_Handler(), and hadc1.
Referenced by main().
MX_ADC2_Init()
void MX_ADC2_Init (void)
Configure the global features of the ADC (Clock, Resolution, Data Alignment and number of conversion)
Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time.
Definition at line 118 of file adc.c.
References Error_Handler(), and hadc2.
Referenced by main().
Variable Documentation
hadc1
ADC_HandleTypeDef hadc1
Definition at line 27 of file adc.c.
Referenced by HAL_ADC_LevelOutOfWindowCallback(), and MX_ADC1_Init().
hadc2
ADC_HandleTypeDef hadc2
Definition at line 28 of file adc.c.
Referenced by HAL_TIM_PeriodElapsedCallback(), and MX_ADC2_Init().
hdma_adc1
DMA_HandleTypeDef hdma_adc1
Definition at line 29 of file adc.c.
Referenced by DMA2_Stream0_IRQHandler(), and HAL_ADC_MspInit().