EVRTOSProject: Core/Inc/can.h File Reference
can.h File Reference
This file contains all the function prototypes for the can.c file.
#include "main.h"
#include "constants.h"
#include "uvfr_utils.h"
Macros
#define CAN_TX_DAEMON_NAME "CanTxDaemon"
#define CAN_RX_DAEMON_NAME "CanRxDaemon"
Typedefs
typedef struct uv_CAN_msg uv_CAN_msg
typedef enum uv_status_t uv_status
Functions
void MX_CAN2_Init (void)
void HAL_CAN_RxFifo0MsgPendingCallback (CAN_HandleTypeDef *hcan2)
void HAL_CAN_RxFifo1MsgPendingCallback (CAN_HandleTypeDef *hcan2)
uv_status uvSendCanMSG (uv_CAN_msg *msg)
Function to send CAN message.
void CANbusTxSvcDaemon (void *args)
Background task that handles any CAN messages that are being sent.
void CANbusRxSvcDaemon (void *args)
Background task that executes the CAN message callback functions.
void insertCANMessageHandler (uint32_t id, void *handlerfunc)
Function to insert an id and function into the lookup table of callback functions.
void nuke_hash_table ()
Variables
CAN_HandleTypeDef hcan2
Detailed Description
This file contains all the function prototypes for the can.c file.
Attention
Copyright (c) 2023 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
‍/ /* USER CODE END Header
Definition in file can.h.
Macro Definition Documentation
CAN_RX_DAEMON_NAME
#define CAN_RX_DAEMON_NAME "CanRxDaemon"
Definition at line 41 of file can.h.
CAN_TX_DAEMON_NAME
#define CAN_TX_DAEMON_NAME "CanTxDaemon"
Definition at line 40 of file can.h.
Typedef Documentation
uv_CAN_msg
typedef struct uv_CAN_msg uv_CAN_msg
Definition at line 43 of file can.h.
uv_status
typedef enum uv_status_t uv_status
Definition at line 44 of file can.h.
Function Documentation
CANbusRxSvcDaemon()
void CANbusRxSvcDaemon (void * args)
Background task that executes the CAN message callback functions.
Basically just snoops through the hash table
Definition at line 618 of file can.c.
References callback_table_mutex, callFunctionFromCANid(), uv_task_info::cmd_data, killSelf(), Rx_msg_queue, suspendSelf(), uv_task_info::task_handle, UV_KILL_CMD, UV_OK, and UV_SUSPEND_CMD.
Referenced by uvSVCTaskManager().
CANbusTxSvcDaemon()
void CANbusTxSvcDaemon (void * args)
Background task that handles any CAN messages that are being sent.
This task sits idle, until the time is right (it receives a notification from the uvSendCanMSG function) Once this condition has been met, it will actually call the HAL_CAN_AddTxMessage function. This is a very high priority task, meaning that it will pause whatever other code is going in order to run
Definition at line 551 of file can.c.
References uv_task_info::cmd_data, uv_CAN_msg::data, uv_CAN_msg::dlc, uv_CAN_msg::flags, hcan2, killSelf(), uv_CAN_msg::msg_id, suspendSelf(), Tx_msg_queue, TxHeader, TxMailbox, UV_CAN_EXTENDED_ID, UV_KILL_CMD, and UV_SUSPEND_CMD.
Referenced by uvSVCTaskManager().
HAL_CAN_RxFifo0MsgPendingCallback()
void HAL_CAN_RxFifo0MsgPendingCallback (CAN_HandleTypeDef * hcan2)
Definition at line 298 of file can.c.
References uv_CAN_msg::data, uv_CAN_msg::dlc, Error_Handler(), hcan2, uv_CAN_msg::msg_id, Rx_msg_queue, and RxHeader.
HAL_CAN_RxFifo1MsgPendingCallback()
void HAL_CAN_RxFifo1MsgPendingCallback (CAN_HandleTypeDef * hcan2)
Definition at line 338 of file can.c.
MX_CAN2_Init()
void MX_CAN2_Init (void)
Definition at line 150 of file can.c.
References Error_Handler(), hcan2, and TxHeader.
Referenced by main().
nuke_hash_table()
void nuke_hash_table ()
Function to free all malloced memory Index through the hash table and free all the malloced memory at each index
Definition at line 453 of file can.c.
References CAN_callback_table, CAN_Callback::next, and table_size.
Variable Documentation
hcan2
CAN_HandleTypeDef hcan2
Definition at line 147 of file can.c.
Referenced by IMD_Request_Status(), main(), MC_Request_Data(), MotorControllerSpinTest(), PDU_disable_brake_light(), PDU_disable_coolant_pump(), PDU_disable_cooling_fans(), PDU_disable_motor_controller(), PDU_disable_shutdown_circuit(), PDU_enable_brake_light(), PDU_enable_coolant_pump(), PDU_enable_cooling_fans(), PDU_enable_motor_controller(), PDU_enable_shutdown_circuit(), PDU_speaker_chirp(), Update_Batt_Temp(), Update_RPM(), and Update_State_Of_Charge().