EVRTOSProject: Core/Src/daq.c File Reference
daq.c File Reference
#include "uvfr_utils.h"
#include "daq.h"
Macros
#define _SRC_UVFR_DAQ
Functions
void deleteParamList ()
void deleteDaqSubTask ()
uv_status startDaqSubTasks ()
uv_status stopDaqSubTasks ()
uv_status initDaqTask (void *args)
initializes the master DAQ task, all that fun stuff. This task probably manages a while plethora of smaller tasks
void daqMasterTask (void *args)
void daqSubTask (void *args)
Variables
void * param_LUT [126]
Macro Definition Documentation
_SRC_UVFR_DAQ
#define _SRC_UVFR_DAQ
Definition at line 1 of file daq.c.
Function Documentation
daqMasterTask()
void daqMasterTask (void * args)
These here lines set the delay. This task executes exactly at the period specified, regardless of how long the task execution actually takes
 */
TickType_t tick_period = pdMS_TO_TICKS(params->task_period); //Convert ms of period to the RTOS ticks
//TickType_t last_time = xTaskGetTickCount();       /**
Definition at line 62 of file daq.c.
References changeVehicleState(), uv_task_info::cmd_data, killSelf(), suspendSelf(), uv_task_info::task_period, UV_DRIVING, UV_ERROR_STATE, UV_KILL_CMD, UV_READY, UV_SUSPEND_CMD, and vehicle_state.
Referenced by initDaqTask().
daqSubTask()
void daqSubTask (void * args)
Definition at line 103 of file daq.c.
deleteDaqSubTask()
void deleteDaqSubTask ()
Definition at line 13 of file daq.c.
deleteParamList()
void deleteParamList ()
Definition at line 9 of file daq.c.
initDaqTask()
uv_status initDaqTask (void * args)
initializes the master DAQ task, all that fun stuff. This task probably manages a while plethora of smaller tasks
This is a fairly standard function
Definition at line 30 of file daq.c.
References _UV_DEFAULT_TASK_STACK_SIZE, uv_task_info::active_states, daqMasterTask(), uv_task_info::deletion_states, PROGRAMMING, uv_task_info::stack_size, uv_task_info::suspension_states, uv_task_info::task_args, uv_task_info::task_function, uv_task_info::task_name, uv_task_info::task_period, uv_task_info::task_priority, UV_DRIVING, UV_ERROR, UV_ERROR_STATE, UV_LAUNCH_CONTROL, UV_OK, UV_READY, and uvCreateTask().
Referenced by uvInitStateEngine().
startDaqSubTasks()
uv_status startDaqSubTasks ()
Definition at line 17 of file daq.c.
References UV_ERROR.
stopDaqSubTasks()
uv_status stopDaqSubTasks ()
Definition at line 21 of file daq.c.
References UV_ERROR.
Variable Documentation
param_LUT
void* param_LUT[126]
Definition at line 7 of file daq.c.