EVRTOSProject: Core/Inc/daq.h File Reference
daq.h File Reference
#include "uvfr_utils.h"
#include "rb_tree.h"
Data Structures
struct daq_param_list_node
struct daq_datapoint
This struct holds info of what needs to be logged.
struct daq_loop_args
struct daq_child_task
Macros
#define _NUM_LOGGABLE_PARAMS
Typedefs
typedef struct daq_param_list_node daq_param_list_node
typedef struct daq_datapoint daq_datapoint
This struct holds info of what needs to be logged.
typedef struct daq_loop_args daq_loop_args
typedef struct daq_child_task daq_child_task
Enumerations
enum loggable_params {
MOTOR_RPM, MOTOR_TEMP, MOTOR_CURRENT, MC_VOLTAGE,
MC_CURRENT, MC_TEMP, MC_ERRORS, BMS_CURRENT,
BMS_VOLTAGE, BMS_ERRORS, MAX_CELL_TEMP, MIN_CELL_TEMP,
AVG_CELL_TEMP, ACC_POWER, ACC_POWER_LIMIT, APPS1_ADC_VAL,
APPS2_ADC_VAL, BPS1_ADC_VAL, BPS2_ADC_VAL, ACCELERATOR_PEDAL_RATIO,
BRAKE_PRESSURE_PA, POWER_DERATE_FACTOR, CURRENT_DRIVING_MODE, MAX_LOGGABLE_PARAMS
}
Functions
enum uv_status_t initDaqTask (void *args)
initializes the master DAQ task, all that fun stuff. This task probably manages a while plethora of smaller tasks
void daqMasterTask (void *args)
Variables
void * param_LUT [126]
Macro Definition Documentation
_NUM_LOGGABLE_PARAMS
#define _NUM_LOGGABLE_PARAMS
Definition at line 14 of file daq.h.
Typedef Documentation
daq_child_task
typedef struct daq_child_task daq_child_task
daq_datapoint
typedef struct daq_datapoint daq_datapoint
This struct holds info of what needs to be logged.
daq_loop_args
typedef struct daq_loop_args daq_loop_args
daq_param_list_node
typedef struct daq_param_list_node daq_param_list_node
Enumeration Type Documentation
loggable_params
enum loggable_params
Enumerator
MOTOR_RPM
MOTOR_TEMP
MOTOR_CURRENT
MC_VOLTAGE
MC_CURRENT
MC_TEMP
MC_ERRORS
BMS_CURRENT
BMS_VOLTAGE
BMS_ERRORS
MAX_CELL_TEMP
MIN_CELL_TEMP
AVG_CELL_TEMP
ACC_POWER
ACC_POWER_LIMIT
APPS1_ADC_VAL
APPS2_ADC_VAL
BPS1_ADC_VAL
BPS2_ADC_VAL
ACCELERATOR_PEDAL_RATIO
BRAKE_PRESSURE_PA
POWER_DERATE_FACTOR
CURRENT_DRIVING_MODE
MAX_LOGGABLE_PARAMS
Definition at line 18 of file daq.h.
Function Documentation
daqMasterTask()
void daqMasterTask (void * args)
These here lines set the delay. This task executes exactly at the period specified, regardless of how long the task execution actually takes
 */
TickType_t tick_period = pdMS_TO_TICKS(params->task_period); //Convert ms of period to the RTOS ticks
//TickType_t last_time = xTaskGetTickCount();       /**
Definition at line 62 of file daq.c.
References changeVehicleState(), uv_task_info::cmd_data, killSelf(), suspendSelf(), uv_task_info::task_period, UV_DRIVING, UV_ERROR_STATE, UV_KILL_CMD, UV_READY, UV_SUSPEND_CMD, and vehicle_state.
Referenced by initDaqTask().
initDaqTask()
enum uv_status_t initDaqTask (void * args)
initializes the master DAQ task, all that fun stuff. This task probably manages a while plethora of smaller tasks
This is a fairly standard function
Definition at line 30 of file daq.c.
References _UV_DEFAULT_TASK_STACK_SIZE, uv_task_info::active_states, daqMasterTask(), uv_task_info::deletion_states, PROGRAMMING, uv_task_info::stack_size, uv_task_info::suspension_states, uv_task_info::task_args, uv_task_info::task_function, uv_task_info::task_name, uv_task_info::task_period, uv_task_info::task_priority, UV_DRIVING, UV_ERROR, UV_ERROR_STATE, UV_LAUNCH_CONTROL, UV_OK, UV_READY, and uvCreateTask().
Referenced by uvInitStateEngine().
Variable Documentation
param_LUT
void* param_LUT[126]
Definition at line 7 of file daq.c.