EVRTOSProject: Core/Inc/dash.h File Reference
dash.h File Reference
#include "main.h"
Enumerations
enum dash_can_ids { Dash_RPM = 0x80, Dash_Battery_Temperature = 0x82, Dash_Motor_Temperature = 0x88, Dash_State_of_Charge = 0x87 }
Functions
void Update_RPM (int16_t value)
void Update_Batt_Temp (uint8_t value)
void Update_State_Of_Charge (uint8_t value)
Enumeration Type Documentation
dash_can_ids
enum dash_can_ids
Enumerator
Dash_RPM
Dash_Battery_Temperature
Dash_Motor_Temperature
Dash_State_of_Charge
Definition at line 14 of file dash.h.
Function Documentation
Update_Batt_Temp()
void Update_Batt_Temp (uint8_t value)
Definition at line 29 of file dash.c.
References Dash_Battery_Temperature, Error_Handler(), hcan2, TxData, TxHeader, and TxMailbox.
Update_RPM()
void Update_RPM (int16_t value)
Definition at line 9 of file dash.c.
References Dash_RPM, Error_Handler(), hcan2, TxData, TxHeader, and TxMailbox.
Referenced by main().
Update_State_Of_Charge()
void Update_State_Of_Charge (uint8_t value)
Definition at line 48 of file dash.c.
References Dash_State_of_Charge, Error_Handler(), hcan2, TxData, TxHeader, and TxMailbox.