EVRTOSProject: Core/Src/driving_loop.c File Reference
driving_loop.c File Reference
File containing the meat and potatoes driving loop thread, and all supporting functions.
#include "main.h"
#include "uvfr_utils.h"
#include "can.h"
#include "motor_controller.h"
#include "FreeRTOS.h"
#include "task.h"
#include "cmsis_os.h"
#include "driving_loop.h"
Functions
enum uv_status_t initDrivingLoop (void *argument)
void StartDrivingLoop (void *argument)
Function implementing the ledTask thread.
Variables
uint16_t adc1_APPS1
uint16_t adc1_APPS2
uint16_t adc1_BPS1
uint16_t adc1_BPS2
Detailed Description
File containing the meat and potatoes driving loop thread, and all supporting functions.
Definition in file driving_loop.c.
Function Documentation
initDrivingLoop()
enum uv_status_t initDrivingLoop (void * argument)
Definition at line 25 of file driving_loop.c.
References uv_task_info::active_states, uv_task_info::deletion_states, PROGRAMMING, uv_task_info::stack_size, StartDrivingLoop(), uv_task_info::suspension_states, uv_task_info::task_args, uv_task_info::task_function, uv_task_info::task_name, uv_task_info::task_period, uv_task_info::task_priority, UV_DRIVING, UV_ERROR, UV_ERROR_STATE, UV_INIT, UV_LAUNCH_CONTROL, UV_OK, UV_READY, UV_SUSPENDED, and uvCreateTask().
Referenced by uvInitStateEngine().
StartDrivingLoop()
void StartDrivingLoop (void * argument)
Function implementing the ledTask thread.
Parameters
argument Not used for now. Will have configuration settings later.
Return values
None This function is made to be the meat and potatoes of the entire vehicle.
The first thing we do here is create some local variables here, to cache whatever variables need cached. We will be caching variables that are used very frequently in every single loop iteration, and are not
This line extracts the specific driving loop parameters as specified in the vehicle settings
 */
driving_loop_args* dl_params = (driving_loop_args*) params->task_args;
/**
These here lines set the delay. This task executes exactly at the period specified, regardless of how long the task execution actually takes
 */
TickType_t tick_period = pdMS_TO_TICKS(params->task_period); //Convert ms of period to the RTOS ticks
TickType_t last_time = xTaskGetTickCount();
/**
Brake Plausibility Check
The way that this works is that if the brake pressure is greater than some threshold, and the accelerator pedal position is also greater than some threshold, the thing will register that a brake implausibility has occurred. This is not very cash money.
If this happens, we want to set the torque/speed output to zero. This will only reset itself once the brakes are set to less than a certain threshold. Honestly evil.
Definition at line 68 of file driving_loop.c.
References adc1_APPS1, adc1_APPS2, adc1_BPS1, adc1_BPS2, driving_loop_args::apps_plausibility_check_threshold, driving_loop_args::bps_plausibility_check_threshold, uv_task_info::cmd_data, Implausible, killSelf(), driving_loop_args::max_apps_offset, driving_loop_args::max_apps_value, driving_loop_args::max_BPS_value, Plausible, suspendSelf(), uv_task_info::task_args, uv_task_info::task_period, UV_KILL_CMD, and UV_SUSPEND_CMD.
Referenced by initDrivingLoop().
Variable Documentation
adc1_APPS1
uint16_t adc1_APPS1
Definition at line 64 of file main.c.
Referenced by HAL_ADC_ConvCpltCallback(), HAL_ADC_LevelOutOfWindowCallback(), main(), and StartDrivingLoop().
adc1_APPS2
uint16_t adc1_APPS2
Definition at line 65 of file main.c.
Referenced by HAL_ADC_ConvCpltCallback(), HAL_ADC_LevelOutOfWindowCallback(), main(), and StartDrivingLoop().
adc1_BPS1
uint16_t adc1_BPS1
Definition at line 66 of file main.c.
Referenced by HAL_ADC_ConvCpltCallback(), and StartDrivingLoop().
adc1_BPS2
uint16_t adc1_BPS2
Definition at line 67 of file main.c.
Referenced by HAL_ADC_ConvCpltCallback(), and StartDrivingLoop().