EVRTOSProject: Core/Inc/driving_loop.h File Reference
driving_loop.h File Reference
#include "motor_controller.h"
#include "uvfr_utils.h"
Data Structures
struct linear_torque_map_args
struct exp_torque_map_args
struct to hold parameters used in an exponential torque map
struct s_curve_torque_map_args
struct for s-curve parameters for torque
union drivingModeParams
this struct is designed to hold information about each drivingmode's map params
struct drivingMode
This is where the driving mode and the drivingModeParams are at.
struct driving_loop_args
Typedefs
typedef uint16_t MC_Torque
typedef uint16_t MC_RPM
typedef uint16_t MC_POWER
typedef struct linear_torque_map_args linear_torque_map_args
typedef struct exp_torque_map_args exp_torque_map_args
struct to hold parameters used in an exponential torque map
typedef struct s_curve_torque_map_args s_curve_torque_map_args
struct for s-curve parameters for torque
typedef union drivingModeParams drivingModeParams
this struct is designed to hold information about each drivingmode's map params
typedef struct drivingMode drivingMode
This is where the driving mode and the drivingModeParams are at.
typedef struct driving_loop_args driving_loop_args
Enumerations
enum map_mode {
linear_speed_map, s_curve_speed_map, exp_speed_map, linear_torque_map,
s_curve_torque_map, exp_torque_map
}
DL_PERIOD is meant to represent how often the driving loop executes, in ms.
enum DL_internal_state { Plausible = 0x01, Implausible = 0x02, Erroneous = 0x04 }
Functions
enum uv_status_t initDrivingLoop (void *argument)
void StartDrivingLoop (void *argument)
Function implementing the ledTask thread.
Typedef Documentation
driving_loop_args
typedef struct driving_loop_args driving_loop_args
drivingMode
typedef struct drivingMode drivingMode
This is where the driving mode and the drivingModeParams are at.
drivingModeParams
typedef union drivingModeParams drivingModeParams
this struct is designed to hold information about each drivingmode's map params
exp_torque_map_args
typedef struct exp_torque_map_args exp_torque_map_args
struct to hold parameters used in an exponential torque map
linear_torque_map_args
typedef struct linear_torque_map_args linear_torque_map_args
MC_POWER
typedef uint16_t MC_POWER
Definition at line 16 of file driving_loop.h.
MC_RPM
typedef uint16_t MC_RPM
Definition at line 15 of file driving_loop.h.
MC_Torque
typedef uint16_t MC_Torque
Definition at line 14 of file driving_loop.h.
s_curve_torque_map_args
typedef struct s_curve_torque_map_args s_curve_torque_map_args
struct for s-curve parameters for torque
Enumeration Type Documentation
DL_internal_state
enum DL_internal_state
Enumerator
Plausible
Implausible
Erroneous
Definition at line 42 of file driving_loop.h.
map_mode
enum map_mode
DL_PERIOD is meant to represent how often the driving loop executes, in ms.
This is a define since I would eventually like this to be configurable via a global variable, or possible be dynamic in the future.
Just replace the number with the name of the variable, and you're all set.
enum meant to represent the different types of pedal map
This enum is meant to represent different functions that map the torque to speed.
Enumerator
linear_speed_map
s_curve_speed_map
exp_speed_map
linear_torque_map
s_curve_torque_map
exp_torque_map
Definition at line 33 of file driving_loop.h.
Function Documentation
initDrivingLoop()
enum uv_status_t initDrivingLoop (void * argument)
Definition at line 25 of file driving_loop.c.
References uv_task_info::active_states, uv_task_info::deletion_states, PROGRAMMING, uv_task_info::stack_size, StartDrivingLoop(), uv_task_info::suspension_states, uv_task_info::task_args, uv_task_info::task_function, uv_task_info::task_name, uv_task_info::task_period, uv_task_info::task_priority, UV_DRIVING, UV_ERROR, UV_ERROR_STATE, UV_INIT, UV_LAUNCH_CONTROL, UV_OK, UV_READY, UV_SUSPENDED, and uvCreateTask().
Referenced by uvInitStateEngine().
StartDrivingLoop()
void StartDrivingLoop (void * argument)
Function implementing the ledTask thread.
Parameters
argument Not used for now. Will have configuration settings later.
Return values
None This function is made to be the meat and potatoes of the entire vehicle.
The first thing we do here is create some local variables here, to cache whatever variables need cached. We will be caching variables that are used very frequently in every single loop iteration, and are not
This line extracts the specific driving loop parameters as specified in the vehicle settings
 */
driving_loop_args* dl_params = (driving_loop_args*) params->task_args;
/**
These here lines set the delay. This task executes exactly at the period specified, regardless of how long the task execution actually takes
 */
TickType_t tick_period = pdMS_TO_TICKS(params->task_period); //Convert ms of period to the RTOS ticks
TickType_t last_time = xTaskGetTickCount();
/**
Brake Plausibility Check
The way that this works is that if the brake pressure is greater than some threshold, and the accelerator pedal position is also greater than some threshold, the thing will register that a brake implausibility has occurred. This is not very cash money.
If this happens, we want to set the torque/speed output to zero. This will only reset itself once the brakes are set to less than a certain threshold. Honestly evil.
Definition at line 68 of file driving_loop.c.
References adc1_APPS1, adc1_APPS2, adc1_BPS1, adc1_BPS2, driving_loop_args::apps_plausibility_check_threshold, driving_loop_args::bps_plausibility_check_threshold, uv_task_info::cmd_data, Implausible, killSelf(), driving_loop_args::max_apps_offset, driving_loop_args::max_apps_value, driving_loop_args::max_BPS_value, Plausible, suspendSelf(), uv_task_info::task_args, uv_task_info::task_period, UV_KILL_CMD, and UV_SUSPEND_CMD.
Referenced by initDrivingLoop().