EVRTOSProject: Core/Src/freertos.c File Reference
freertos.c File Reference
#include "FreeRTOS.h"
#include "task.h"
#include "main.h"
#include "cmsis_os.h"
#include "uvfr_utils.h"
Functions
void StartDefaultTask (void const *argument)
Function implementing the defaultTask thread.
void MX_FREERTOS_Init (void)
FreeRTOS initialization.
void vApplicationGetIdleTaskMemory (StaticTask_t **ppxIdleTaskTCBBuffer, StackType_t **ppxIdleTaskStackBuffer, uint32_t *pulIdleTaskStackSize)
void vApplicationGetTimerTaskMemory (StaticTask_t **ppxTimerTaskTCBBuffer, StackType_t **ppxTimerTaskStackBuffer, uint32_t *pulTimerTaskStackSize)
void vApplicationTickHook (void)
void vApplicationStackOverflowHook (TaskHandle_t xTask, signed char *pcTaskName)
void vApplicationMallocFailedHook (void)
void vApplicationIdleHook (void)
Variables
uv_init_struct init_settings
TaskHandle_t init_task_handle
osThreadId defaultTaskHandle
static StaticTask_t xIdleTaskTCBBuffer
static StackType_t xIdleStack [configMINIMAL_STACK_SIZE]
static StaticTask_t xTimerTaskTCBBuffer
static StackType_t xTimerStack [configTIMER_TASK_STACK_DEPTH]
Function Documentation
MX_FREERTOS_Init()
void MX_FREERTOS_Init (void)
FreeRTOS initialization.
Parameters
None
Return values
None
Attention
DONT YOU FUCKING DARE DELETE THESE GOTO STATEMENTS, THEY ARE CRITICAL TO STOP THE OS FROM HANGING ITSELF
Definition at line 160 of file freertos.c.
References defaultTaskHandle, init_settings, init_task_handle, StartDefaultTask(), uv_init_struct::use_default_settings, and uvInit().
Referenced by main().
StartDefaultTask()
void StartDefaultTask (void const * argument)
Function implementing the defaultTask thread.
Attention
DO NOT EVER CALL THIS. IT EXISTS TO STOP A COMPILER ERROR IN THE MX_FREERTOS_INIT FUNCTION
Definition at line 209 of file freertos.c.
Referenced by MX_FREERTOS_Init().
vApplicationGetIdleTaskMemory()
void vApplicationGetIdleTaskMemory (StaticTask_t ** ppxIdleTaskTCBBuffer, StackType_t ** ppxIdleTaskStackBuffer, uint32_t * pulIdleTaskStackSize)
Definition at line 132 of file freertos.c.
References configMINIMAL_STACK_SIZE, xIdleStack, and xIdleTaskTCBBuffer.
vApplicationGetTimerTaskMemory()
void vApplicationGetTimerTaskMemory (StaticTask_t ** ppxTimerTaskTCBBuffer, StackType_t ** ppxTimerTaskStackBuffer, uint32_t * pulTimerTaskStackSize)
Definition at line 146 of file freertos.c.
References configTIMER_TASK_STACK_DEPTH, xTimerStack, and xTimerTaskTCBBuffer.
vApplicationIdleHook()
void vApplicationIdleHook (void)
Definition at line 101 of file freertos.c.
vApplicationMallocFailedHook()
__weak void vApplicationMallocFailedHook (void)
Definition at line 108 of file freertos.c.
vApplicationStackOverflowHook()
__weak void vApplicationStackOverflowHook (TaskHandle_t xTask, signed char * pcTaskName)
Definition at line 89 of file freertos.c.
vApplicationTickHook()
__weak void vApplicationTickHook (void)
Definition at line 76 of file freertos.c.
Variable Documentation
defaultTaskHandle
osThreadId defaultTaskHandle
Definition at line 53 of file freertos.c.
Referenced by MX_FREERTOS_Init().
init_settings
uv_init_struct init_settings
File Name : freertos.c Description : Code for freertos applications
Attention
Copyright (c) 2024 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition at line 48 of file freertos.c.
Referenced by MX_FREERTOS_Init().
init_task_handle
TaskHandle_t init_task_handle
Definition at line 51 of file freertos.c.
Referenced by MX_FREERTOS_Init(), and uvInit().
xIdleStack
StackType_t xIdleStack[configMINIMAL_STACK_SIZE] static
Definition at line 130 of file freertos.c.
Referenced by vApplicationGetIdleTaskMemory().
xIdleTaskTCBBuffer
StaticTask_t xIdleTaskTCBBuffer static
Definition at line 129 of file freertos.c.
Referenced by vApplicationGetIdleTaskMemory().
xTimerStack
StackType_t xTimerStack[configTIMER_TASK_STACK_DEPTH] static
Definition at line 144 of file freertos.c.
Referenced by vApplicationGetTimerTaskMemory().
xTimerTaskTCBBuffer
StaticTask_t xTimerTaskTCBBuffer static
Definition at line 143 of file freertos.c.
Referenced by vApplicationGetTimerTaskMemory().