EVRTOSProject: State Engine Internals
State Engine Internals
State Engine
Functions
uv_status addTaskToTaskRegister (uv_task_id id, uint8_t assign_to_whom)
uv_status _uvValidateSpecificTask (uv_task_id id)
make sure the parameters of a task_info struct is valid
uv_status uvValidateManagedTasks ()
ensure that all the tasks people have created actually make sense, and are valid
uv_status uvStartTask (uint32_t *tracker, uv_task_info *t)
: This is a function that starts tasks which are already registered in the system
static uv_status uvKillTaskViolently (uv_task_info *t)
if a task refuses to comply with the SCD, then it has no choice but to be deleted. There is nothing that can be done.
uv_status uvDeleteTask (uint32_t *tracker, uv_task_info *t)
deletes a managed task via the system
uv_status uvAbortTaskDeletion (uv_task_info *t)
If a task is scheduled for deletion, we want to be able to resurrect it.
uv_status uvScheduleTaskDeletion (uint32_t *tracker, uv_task_info *t)
Schedule a task to be deleted in the future double plus ungood imho.
uv_status uvSuspendTask (uint32_t *tracker, uv_task_info *t)
function to suspend one of the managed tasks.
uv_status uvTaskCrashHandler (uv_task_info *t)
Called when a task has crashed and we need to figure out what to do with it.
void __uvPanic (char *msg, uint8_t msg_len, const char *file, const int line, const char *func)
Something bad has occurred here now we in trouble.
void killSelf (uv_task_info *t)
This function is called by a task to nuke itself. Is a wrapper function that is used to do all the different things.
void suspendSelf (uv_task_info *t)
Called by a task that needs to suspend itself, once the task has determined it is safe to do so.
static uv_status proccessSCDMsg (uv_scd_response *msg)
Helper function for the SCD, that proccesses a message, and double checks to make sure the task that sent the message isn't straight up lying to us.
void uvSendTaskStatusReport (uv_task_info *t)
void _stateChangeDaemon (void *args) PRIVILEGED_FUNCTION
This collects all the data changing from different tasks, and makes sure that everything works properly.
uv_status uvThrottleNonCritTasks ()
void uvLateTaskHandler (uv_task_info *t, TickType_t tdiff, uint8_t task_tardiness)
uv_task_info * uvCreateServiceTask ()
Create a new service task, because fuck you, thats why.
uv_status uvStartSVCTask (uv_task_info *t)
Function to start a service task specifically.
uv_status uvSuspendSVCTask (uv_task_info *t)
Function that suspends a service task.
uv_status uvDeleteSVCTask (uv_task_info *t)
For when you need to delete a service task... for some reason...
uv_status uvRestartSVCTask (uv_task_info *t)
Function that takes a service part that may be messed up and tries to reboot it to recover.
uv_task_info * uvGetTaskFromName (char *tsk_name)
uv_task_info * uvGetTaskFromRTOSHandle (TaskHandle_t t_handle)
Returns the pointer to the task info structure.
uv_status killEmAll ()
The name should be pretty self explanatory.
void uvTaskManager (void *args) PRIVILEGED_FUNCTION
The big papa task that deals with handling all of the others.
Detailed Description
Attention
Do not edit these functions, or even contemplate calling one of them directly unless you 100% know what you are doing. These are DANGEROUS
This handles all the under the hood bullshit inherent to a system that dynamically starts and restarts RTOS tasks. Due to this being a safety critical system, great care must be taken to prevent the vehicle from entering an unsafe state as a result of anything happening in these functions.
Function Documentation
__uvPanic()
void __uvPanic (char * msg, uint8_t msg_len, const char * file, const int line, const char * func)
Something bad has occurred here now we in trouble.
General idea here: Something bad has happened that is severe enough that it requires the shutdown of the vehicle. This can mean several things, such as being on fire, etc... that need to be appropriately handled
This should also log whatever the fuck happened.
The following should happen, in order:
Forcibly put vehicle into a safe state
Change vehicle state to error, and invoke the SCD
Log the error in our lil running journal
Should change vehicle state itself be the source of the error, we just need the software to completely fucking hang itself. If things are so fucked that we genuinely cannot even transition to the error state, then get that shit the fuck outta here, we shuttin down fr fr.
Definition at line 686 of file uvfr_state_engine.c.
References changeVehicleState(), UV_ERROR_STATE, and uvSecureVehicle().
_stateChangeDaemon()
void _stateChangeDaemon (void * args)
This collects all the data changing from different tasks, and makes sure that everything works properly.
Attention
DO NOT EVER JUST CALL THIS FUNCTION. THIS SHOULD ONLY BE CALLED FROM changeVehicleState
Parameters
args This accepts a void* pointer to avoid compile errors with freeRTOS, since freeRTOS expects a pointer to the function that accepts a void pointer
This is a one-shot RTOS task that spawns in when we want to change the state of the vehicle state. It performs this in the following way
We get to iterate through all of the managed tasks. Goes via IDs as well. We load up the array entry as a temp pointer to a task info struct. As we go through it determines what to do by comparing the uv_task_info.active_states as well as uv_task_info.deletion_states and uv_task_info.suspension_states with uv_vehicle_state
This is done with the bitwise & operator, since the definition of the uv_vehicle_state_t enum facilitates this by only using factors of two.
Acquires pointer to task definition struct, then sets the queue in the struct to the SCD queue, so that the task actually does task things. Love when that happens. Next it sets the bit in the task_tracker corresponding to the task id, therefore marking that some action must be taken to either
confirm that no action is neccessary
bring the task state into the correct state
Now we suspend the task because it has been misbehaving in school
Wait for all the tasks that had changes made to respond.
 */
    uv_scd_response* response = NULL;
    for(int i = 0; i < _LONGEST_SC_TIME/_SC_DAEMON_PERIOD; i++){ //This loop verifies to make sure things are actually chillin
        vTaskDelay(_SC_DAEMON_PERIOD);
        for(int j = 0;j<10;j++){ //What kinda magic number is this? Why 10?
            if(xQueueReceive(state_change_queue,&response,1) == pdPASS){
                if(response == NULL){//definately not supposed to happen
                    uvPanic("null scd response",0);
                }
                if(proccessSCDMsg(response)==UV_OK){
                    task_tracker &= ~(0x01<<response->meta_id);
                    if (_task_register[response->meta_id].task_state == UV_TASK_DELETED){
                        _task_register[response->meta_id].task_handle = NULL;
                    }
                }else{
                    //Not ok, this means that process SCD has returned something weird. More detailed error_handling can be added later.
                    uvPanic("Task giving Sass to SCD",0);
                }
                if(uvFree(response)!=UV_OK){
                    uvPanic("failed to free memory", 0);
                }
                    response = NULL;
                }else{
                    break;
                }
        }
    }
    //You timed out didnt you... Naughty naughty...
    if(task_tracker != 0){
        uvPanic("SCD Timeout",0);
    }
    //TODO: Forcibly reconcile vehicle state, and nuke whatever tasks require nuking, suspend whatever needs suspended
    //END_OF_STATE_CHANGE_DAEMON:
//}
TaskHandle_t scd_handle = ((state_change_daemon_args*)args)->meta_task_handle;
uvFree(args);
vQueueDelete(state_change_queue);
state_change_queue = NULL;
/**
The final act of the SCD, is to delete itself
 */
vTaskDelete(scd_handle);
Definition at line 865 of file uvfr_state_engine.c.
References _LONGEST_SC_TIME, _next_task_id, _SC_DAEMON_PERIOD, _task_register, uv_task_info::active_states, uv_task_info::deletion_states, uv_scd_response::meta_id, proccessSCDMsg(), SCD_active, state_change_queue, uv_task_info::suspension_states, uv_task_info::task_flags, uv_task_info::task_handle, uv_task_info::task_state, UV_OK, UV_TASK_AWAITING_DELETION, UV_TASK_DEFER_DELETION, UV_TASK_DELETED, UV_TASK_NOT_STARTED, UV_TASK_RUNNING, UV_TASK_SUSPENDED, uvDeleteTask(), uvScheduleTaskDeletion(), uvStartTask(), uvSuspendTask(), and vehicle_state.
Referenced by changeVehicleState().
_uvValidateSpecificTask()
uv_status _uvValidateSpecificTask (uv_task_id id)
make sure the parameters of a task_info struct is valid
Definition at line 323 of file uvfr_state_engine.c.
References _task_register, uv_task_info::active_states, uv_task_info::deletion_states, uv_task_info::suspension_states, uv_task_info::task_function, uv_task_info::task_name, UV_ERROR, and UV_OK.
Referenced by addTaskToTaskRegister(), and uvValidateManagedTasks().
addTaskToTaskRegister()
uv_status addTaskToTaskRegister (uv_task_id id, uint8_t assign_to_whom)
Definition at line 310 of file uvfr_state_engine.c.
References _uvValidateSpecificTask(), and UV_OK.
killEmAll()
uv_status killEmAll ()
The name should be pretty self explanatory.
Definition at line 452 of file uvfr_state_engine.c.
References _BV_32, _next_task_id, _task_register, UV_ERROR, UV_OK, and uvDeleteTask().
Referenced by uvDeInitStateEngine().
killSelf()
void killSelf (uv_task_info * t)
This function is called by a task to nuke itself. Is a wrapper function that is used to do all the different things.
First lets load up the queue and the values in it. These come from the task we are doing.
Definition at line 708 of file uvfr_state_engine.c.
References uv_task_info::cmd_data, uv_scd_response::meta_id, uv_scd_response::response_val, state_change_queue, uv_task_info::task_handle, uv_task_info::task_id, uv_task_info::task_state, UV_NO_CMD, UV_SUCCESSFUL_DELETION, and UV_TASK_DELETED.
Referenced by CANbusRxSvcDaemon(), CANbusTxSvcDaemon(), daqMasterTask(), odometerTask(), StartDrivingLoop(), tempMonitorTask(), and uvTaskManager().
proccessSCDMsg()
static uv_status proccessSCDMsg (uv_scd_response * msg) static
Helper function for the SCD, that proccesses a message, and double checks to make sure the task that sent the message isn't straight up lying to us.
This function is responsible for the following functionality:
Make sure that the message claims that the deletion or suspension of a task is successful
If a task claims that it is deleted, or suspended, then we must verify that this is the case
Get the id of the message, then use that to index the _task_register Mission critical stuff that stops ev from driving into a wall
Definition at line 792 of file uvfr_state_engine.c.
References _task_register, uv_scd_response::meta_id, uv_scd_response::response_val, uv_task_info::task_handle, uv_task_info::task_state, UV_COULDNT_DELETE, UV_COULDNT_SUSPEND, UV_ERROR, UV_OK, UV_SUCCESSFUL_DELETION, UV_SUCCESSFUL_SUSPENSION, UV_TASK_DELETED, and UV_UNSAFE_STATE.
Referenced by _stateChangeDaemon().
suspendSelf()
void suspendSelf (uv_task_info * t)
Called by a task that needs to suspend itself, once the task has determined it is safe to do so.
Definition at line 749 of file uvfr_state_engine.c.
References uv_task_info::cmd_data, uv_scd_response::meta_id, uv_scd_response::response_val, state_change_queue, uv_task_info::task_handle, uv_task_info::task_id, uv_task_info::task_state, UV_NO_CMD, UV_SUCCESSFUL_SUSPENSION, and UV_TASK_SUSPENDED.
Referenced by CANbusRxSvcDaemon(), CANbusTxSvcDaemon(), daqMasterTask(), odometerTask(), StartDrivingLoop(), tempMonitorTask(), and uvTaskManager().
uvAbortTaskDeletion()
uv_status uvAbortTaskDeletion (uv_task_info * t)
If a task is scheduled for deletion, we want to be able to resurrect it.
Calling this will find the task deletion timer, and remove the task from the grave.
Definition at line 557 of file uvfr_state_engine.c.
References UV_ERROR, and UV_OK.
uvCreateServiceTask()
uv_task_info* uvCreateServiceTask ()
Create a new service task, because fuck you, thats why.
Acquire the pointer to the spot in the array, we are doing this since we need to return the pointer anyways, and it cleans up the syntax a little.
Definition at line 1195 of file uvfr_state_engine.c.
References _next_svc_task_id, _next_task_id, _task_register, _UV_DEFAULT_TASK_STACK_SIZE, uv_task_info::active_states, uv_task_info::deletion_states, MAX_NUM_MANAGED_TASKS, uv_task_info::parent, uv_task_info::stack_size, uv_task_info::suspension_states, uv_task_info::task_flags, uv_task_info::task_function, uv_task_info::task_handle, uv_task_info::task_id, uv_task_info::task_name, uv_task_info::task_priority, uv_task_info::task_state, UV_TASK_GENERIC_SVC, UV_TASK_NOT_STARTED, and UV_TASK_SCD_IGNORE.
Referenced by uvInitStateEngine(), and uvSVCTaskManager().
uvDeleteSVCTask()
uv_status uvDeleteSVCTask (uv_task_info * t)
For when you need to delete a service task... for some reason...
Definition at line 1289 of file uvfr_state_engine.c.
References uv_task_info::cmd_data, uv_task_info::task_handle, uv_task_info::task_state, UV_ABORTED, UV_ERROR, UV_KILL_CMD, UV_OK, UV_TASK_DELETED, UV_TASK_NOT_STARTED, UV_TASK_RUNNING, and UV_TASK_SUSPENDED.
Referenced by uvRestartSVCTask().
uvDeleteTask()
uv_status uvDeleteTask (uint32_t * tracker, uv_task_info * t)
deletes a managed task via the system
This function is the lowtier god of the program. It pulls up and is like "YOU SHOULD KILL YOURSELF, NOW!!" It sends a message to the task which tells it to kill itself.
The task complies. It does not have a choice.
This checks with the RTOS kernel to see that the task as stated by the scheduler matches the state known by uvfr_utils
Definition at line 497 of file uvfr_state_engine.c.
References uv_task_info::cmd_data, uv_task_info::task_handle, uv_task_info::task_id, uv_task_info::task_state, UV_ABORTED, UV_ERROR, UV_KILL_CMD, UV_OK, UV_TASK_DELETED, UV_TASK_NOT_STARTED, UV_TASK_SUSPENDED, and uvTaskIsDelaying.
Referenced by _stateChangeDaemon(), and killEmAll().
uvGetTaskFromName()
uv_task_info* uvGetTaskFromName (char * tsk_name)
Sometimes you just gottta deal with it lol
Definition at line 1436 of file uvfr_state_engine.c.
uvGetTaskFromRTOSHandle()
uv_task_info* uvGetTaskFromRTOSHandle (TaskHandle_t t_handle)
Returns the pointer to the task info structure.
Parameters
t_handle A freeRTOS task handle.
Return values
A pointer to a uv_task_info data structure. This is mostly useful for cases where you know the RTOS handle, but not the task info struct
Definition at line 1448 of file uvfr_state_engine.c.
uvKillTaskViolently()
static uv_status uvKillTaskViolently (uv_task_info * t) static
if a task refuses to comply with the SCD, then it has no choice but to be deleted. There is nothing that can be done.
You will not win against the operating system.
The first thing that needs to happen, is we will tell the kernel to release any resources owned by the task.
Definition at line 473 of file uvfr_state_engine.c.
References UV_OK.
Referenced by uvRestartSVCTask().
uvLateTaskHandler()
void uvLateTaskHandler (uv_task_info * t, TickType_t tdiff, uint8_t task_tardiness)
Definition at line 1046 of file uvfr_state_engine.c.
References uv_task_info::task_flags, uv_task_info::task_period, task_tardiness, and UV_TASK_MISSION_CRITICAL.
Referenced by uvTaskManager().
uvRestartSVCTask()
uv_status uvRestartSVCTask (uv_task_info * t)
Function that takes a service part that may be messed up and tries to reboot it to recover.
This may be neccessary if a SVC task is not responding. Be careful though, since this has the potential to delay more important tasks :o Therefore, this technique should be used sparingly, and each task gets a limited number of attempts within a certain time period.
Definition at line 1317 of file uvfr_state_engine.c.
References UV_ERROR, UV_OK, uvDeleteSVCTask(), uvKillTaskViolently(), and uvStartSVCTask().
uvScheduleTaskDeletion()
uv_status uvScheduleTaskDeletion (uint32_t * tracker, uv_task_info * t)
Schedule a task to be deleted in the future double plus ungood imho.
Definition at line 569 of file uvfr_state_engine.c.
References uv_task_info::task_flags, uv_task_info::task_id, uv_task_info::task_state, UV_ABORTED, UV_ERROR, UV_OK, UV_TASK_AWAITING_DELETION, and UV_TASK_DELETED.
Referenced by _stateChangeDaemon().
uvSendTaskStatusReport()
void uvSendTaskStatusReport (uv_task_info * t)
Definition at line 849 of file uvfr_state_engine.c.
uvStartSVCTask()
uv_status uvStartSVCTask (uv_task_info * t)
Function to start a service task specifically.
Definition at line 1235 of file uvfr_state_engine.c.
References uv_task_info::stack_size, uv_task_info::task_args, uv_task_info::task_flags, uv_task_info::task_function, uv_task_info::task_handle, uv_task_info::task_name, uv_task_info::task_priority, uv_task_info::task_state, UV_ABORTED, UV_ERROR, UV_OK, UV_TASK_GENERIC_SVC, UV_TASK_RUNNING, and UV_TASK_SUSPENDED.
Referenced by uvRestartSVCTask().
uvStartTask()
uv_status uvStartTask (uint32_t * tracker, uv_task_info * t)
: This is a function that starts tasks which are already registered in the system
This bad boi gets called from the stateChangeDaemon because it's a special little snowflake.
The first thing we will do is check if the task is running, since this could theoretically get called from literally anywhere. If the task is running, then we check to see if t->task_handle is set to NULL . If it is null, that is a physically impossible_state. Neither very mindful or very demure.
That being said, if the task appears legit, then just update the corresponding bits in the tracker, and return that the task has aborted.
If a task has been suspended, we do not want to create a new instance of the task, becuase then the task will go out of scope, and changing the task handle to a new instance will result in the task never being de-initialized, therefore causing a memory leak. We want to call vTaskResume instead, and just boot the task back into existence.
If none of the previous if statements caught the task handle, then that means that either this is our first time attempting to activate this task, or the task has been deleted at some point prior to this one
Definition at line 380 of file uvfr_state_engine.c.
References _BV_32, uv_task_info::last_execution_time, uv_task_info::stack_size, uv_task_info::task_function, uv_task_info::task_handle, uv_task_info::task_id, uv_task_info::task_name, uv_task_info::task_priority, uv_task_info::task_state, UV_ABORTED, UV_ERROR, UV_OK, UV_TASK_RUNNING, and UV_TASK_SUSPENDED.
Referenced by _stateChangeDaemon(), and uvSVCTaskManager().
uvSuspendSVCTask()
uv_status uvSuspendSVCTask (uv_task_info * t)
Function that suspends a service task.
Definition at line 1274 of file uvfr_state_engine.c.
References uv_task_info::task_state, UV_ABORTED, UV_ERROR, UV_OK, and UV_TASK_SUSPENDED.
uvSuspendTask()
uv_status uvSuspendTask (uint32_t * tracker, uv_task_info * t)
function to suspend one of the managed tasks.
Parameters
tracker is a pointer to an int. If the task actually suspends, we update the tracker, since no further action is needed.
t is a pointer to a uv_task_info struct.
Definition at line 596 of file uvfr_state_engine.c.
References uv_task_info::cmd_data, uv_task_info::task_handle, uv_task_info::task_id, uv_task_info::task_state, UV_ERROR, UV_OK, UV_SUSPEND_CMD, UV_TASK_DELETED, UV_TASK_NOT_STARTED, UV_TASK_SUSPENDED, and uvTaskIsDelaying.
Referenced by _stateChangeDaemon().
uvTaskCrashHandler()
uv_status uvTaskCrashHandler (uv_task_info * t)
Called when a task has crashed and we need to figure out what to do with it.
Effectively, there are a couple variables we care about here: 1) Can the vehicle continue operation without that task active? 2) Do we really care?
If the task is critical, then this needs to 100% result in a panic. If it isn't then we can try to restart the task, noting that this may result in strange undefined behavior down the line. Thankfully if a task is not safety critical, we don't really care whether it misbehaves. Appropriate countermeasures are in place to prevent one task from overflowing into another task, as well as to mitigate against possible memory leaks.
Definition at line 653 of file uvfr_state_engine.c.
References uv_task_info::task_flags, UV_ERROR, UV_OK, and UV_TASK_MISSION_CRITICAL.
uvTaskManager()
void uvTaskManager (void * args)
The big papa task that deals with handling all of the others.
The responsibilities of this task are as follows:
Monitor tasks to ensure they are on schedule
Setup inter-task communication channels?
Invoke SCD if necessary
Track mem usage if needed
This task is one of the most important ones in the system. Lovely times for all. Therefore it us of utmost importance that this one DOES NOT CRASH. EVER.
Definition at line 1080 of file uvfr_state_engine.c.
References _next_task_id, _task_register, uv_task_info::cmd_data, killSelf(), uv_task_info::last_execution_time, last_task_end_times, last_task_start_times, MAX_NUM_MANAGED_TASKS, nc_throttling, os_settings, task_management_info::parent_msg_queue, suspendSelf(), uv_task_info::task_flags, task_management_info::task_handle, uv_task_info::task_handle, uv_os_settings::task_overshoot_margin_crit, uv_os_settings::task_overshoot_margin_noncrit, uv_task_info::task_period, uv_task_info::task_state, task_tardiness, uv_task_info::tmi, UV_INVALID_MSG, UV_KILL_CMD, UV_SUSPEND_CMD, UV_TASK_MANAGER_MASK, UV_TASK_MISSION_CRITICAL, UV_TASK_RUNNING, UV_TASK_VEHICLE_APPLICATION, uvLateTaskHandler(), and uvTaskPeriodEnd().
Referenced by uvStartStateMachine().
uvThrottleNonCritTasks()
uv_status uvThrottleNonCritTasks ()
Definition at line 1041 of file uvfr_state_engine.c.
uvValidateManagedTasks()
uv_status uvValidateManagedTasks ()
ensure that all the tasks people have created actually make sense, and are valid
Definition at line 358 of file uvfr_state_engine.c.
References _next_task_id, _uvValidateSpecificTask(), and UV_OK.
Referenced by uvStartStateMachine().