EVRTOSProject: Core/Inc/main.h File Reference
main.h File Reference
: Header for main.c file. This file contains the common defines of the application.
#include "stm32f4xx_hal.h"
#include <stdarg.h>
#include "uvfr_utils.h"
Macros
#define Start_Button_Input_Pin GPIO_PIN_0
#define Start_Button_Input_GPIO_Port GPIOA
#define Start_Button_Input_EXTI_IRQn EXTI0_IRQn
#define Orange_LED_Pin GPIO_PIN_13
#define Orange_LED_GPIO_Port GPIOD
#define Red_LED_Pin GPIO_PIN_14
#define Red_LED_GPIO_Port GPIOD
#define Blue_LED_Pin GPIO_PIN_15
#define Blue_LED_GPIO_Port GPIOD
Functions
void Error_Handler (void)
This function is executed in case of error occurrence.
Detailed Description
: Header for main.c file. This file contains the common defines of the application.
Attention
Copyright (c) 2023 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file main.h.
Macro Definition Documentation
Blue_LED_GPIO_Port
#define Blue_LED_GPIO_Port GPIOD
Definition at line 72 of file main.h.
Blue_LED_Pin
#define Blue_LED_Pin GPIO_PIN_15
Definition at line 71 of file main.h.
Orange_LED_GPIO_Port
#define Orange_LED_GPIO_Port GPIOD
Definition at line 68 of file main.h.
Orange_LED_Pin
#define Orange_LED_Pin GPIO_PIN_13
Definition at line 67 of file main.h.
Red_LED_GPIO_Port
#define Red_LED_GPIO_Port GPIOD
Definition at line 70 of file main.h.
Red_LED_Pin
#define Red_LED_Pin GPIO_PIN_14
Definition at line 69 of file main.h.
Start_Button_Input_EXTI_IRQn
#define Start_Button_Input_EXTI_IRQn EXTI0_IRQn
Definition at line 66 of file main.h.
Start_Button_Input_GPIO_Port
#define Start_Button_Input_GPIO_Port GPIOA
Definition at line 65 of file main.h.
Start_Button_Input_Pin
#define Start_Button_Input_Pin GPIO_PIN_0
Definition at line 64 of file main.h.
Function Documentation
Error_Handler()
void Error_Handler (void)
This function is executed in case of error occurrence.
Return values
None
Definition at line 378 of file main.c.
Referenced by HAL_ADC_MspInit(), HAL_CAN_RxFifo0MsgPendingCallback(), IMD_Parse_Message(), IMD_Request_Status(), MX_ADC1_Init(), MX_ADC2_Init(), MX_CAN2_Init(), MX_SPI1_Init(), MX_TIM3_Init(), PDU_disable_brake_light(), PDU_disable_coolant_pump(), PDU_disable_cooling_fans(), PDU_disable_motor_controller(), PDU_disable_shutdown_circuit(), PDU_enable_brake_light(), PDU_enable_coolant_pump(), PDU_enable_cooling_fans(), PDU_enable_motor_controller(), PDU_enable_shutdown_circuit(), PDU_speaker_chirp(), SystemClock_Config(), Update_Batt_Temp(), Update_RPM(), and Update_State_Of_Charge().