EVRTOSProject: Core/Src/main.c File Reference
main.c File Reference
: Main program body
#include "main.h"
#include "cmsis_os.h"
#include "adc.h"
#include "can.h"
#include "dma.h"
#include "spi.h"
#include "tim.h"
#include "gpio.h"
#include "constants.h"
#include "bms.h"
#include "dash.h"
#include "imd.h"
#include "motor_controller.h"
#include "pdu.h"
Macros
#define DEBUG_CAN_IN_MAIN 0
Functions
void SystemClock_Config (void)
System Clock Configuration.
void MX_FREERTOS_Init (void)
FreeRTOS initialization.
int main (void)
The application entry point.
void HAL_ADC_ConvCpltCallback (ADC_HandleTypeDef *hadc)
void HAL_GPIO_EXTI_Callback (uint16_t GPIO_Pin)
void HAL_ADC_LevelOutOfWindowCallback (ADC_HandleTypeDef *hadc)
void HAL_TIM_PeriodElapsedCallback (TIM_HandleTypeDef *htim)
Period elapsed callback in non blocking mode.
void Error_Handler (void)
This function is executed in case of error occurrence.
Variables
volatile uint32_t adc_buf1 [ADC1_BUF_LEN]
uint16_t adc1_APPS1
uint16_t adc1_APPS2
uint16_t adc1_BPS1
uint16_t adc1_BPS2
volatile uint32_t adc_buf2 [ADC2_BUF_LEN]
uint16_t adc2_CoolantTemp
uint16_t adc2_CoolantFlow
Detailed Description
: Main program body
Attention
Copyright (c) 2023 STMicroelectronics. All rights reserved.
This software is licensed under terms that can be found in the LICENSE file in the root directory of this software component. If no LICENSE file comes with this software, it is provided AS-IS.
Definition in file main.c.
Macro Definition Documentation
DEBUG_CAN_IN_MAIN
#define DEBUG_CAN_IN_MAIN 0
Definition at line 51 of file main.c.
Function Documentation
Error_Handler()
void Error_Handler (void)
This function is executed in case of error occurrence.
Return values
None
Definition at line 378 of file main.c.
Referenced by HAL_ADC_MspInit(), HAL_CAN_RxFifo0MsgPendingCallback(), IMD_Parse_Message(), IMD_Request_Status(), MX_ADC1_Init(), MX_ADC2_Init(), MX_CAN2_Init(), MX_SPI1_Init(), MX_TIM3_Init(), PDU_disable_brake_light(), PDU_disable_coolant_pump(), PDU_disable_cooling_fans(), PDU_disable_motor_controller(), PDU_disable_shutdown_circuit(), PDU_enable_brake_light(), PDU_enable_coolant_pump(), PDU_enable_cooling_fans(), PDU_enable_motor_controller(), PDU_enable_shutdown_circuit(), PDU_speaker_chirp(), SystemClock_Config(), Update_Batt_Temp(), Update_RPM(), and Update_State_Of_Charge().
HAL_ADC_ConvCpltCallback()
void HAL_ADC_ConvCpltCallback (ADC_HandleTypeDef * hadc)
Definition at line 275 of file main.c.
References adc1_APPS1, adc1_APPS2, adc1_BPS1, adc1_BPS2, ADC1_SAMPLES, adc2_CoolantFlow, adc2_CoolantTemp, adc_buf1, and adc_buf2.
HAL_ADC_LevelOutOfWindowCallback()
void HAL_ADC_LevelOutOfWindowCallback (ADC_HandleTypeDef * hadc)
Definition at line 330 of file main.c.
References adc1_APPS1, adc1_APPS2, hadc1, Red_LED_GPIO_Port, and Red_LED_Pin.
HAL_GPIO_EXTI_Callback()
void HAL_GPIO_EXTI_Callback (uint16_t GPIO_Pin)
Definition at line 321 of file main.c.
HAL_TIM_PeriodElapsedCallback()
void HAL_TIM_PeriodElapsedCallback (TIM_HandleTypeDef * htim)
Period elapsed callback in non blocking mode.
Note
This function is called when TIM1 interrupt took place, inside HAL_TIM_IRQHandler(). It makes a direct call to HAL_IncTick() to increment a global variable "uwTick" used as application time base.
Parameters
htim : TIM handle
Return values
None
Definition at line 354 of file main.c.
References ADC2_BUF_LEN, adc_buf2, hadc2, and htim3.
main()
int main (void)
The application entry point.
Return values
int
Definition at line 97 of file main.c.
References adc1_APPS1, adc1_APPS2, handleCANbusError(), hcan2, MX_ADC1_Init(), MX_ADC2_Init(), MX_CAN2_Init(), MX_DMA_Init(), MX_FREERTOS_Init(), MX_GPIO_Init(), MX_SPI1_Init(), MX_TIM3_Init(), SystemClock_Config(), TxData, TxHeader, TxMailbox, and Update_RPM().
MX_FREERTOS_Init()
void MX_FREERTOS_Init (void)
FreeRTOS initialization.
Parameters
None
Return values
None
Attention
DONT YOU FUCKING DARE DELETE THESE GOTO STATEMENTS, THEY ARE CRITICAL TO STOP THE OS FROM HANGING ITSELF
Definition at line 160 of file freertos.c.
References defaultTaskHandle, init_settings, init_task_handle, StartDefaultTask(), uv_init_struct::use_default_settings, and uvInit().
Referenced by main().
SystemClock_Config()
void SystemClock_Config (void)
System Clock Configuration.
Return values
None
Configure the main internal regulator output voltage
Initializes the RCC Oscillators according to the specified parameters in the RCC_OscInitTypeDef structure.
Initializes the CPU, AHB and APB buses clocks
Definition at line 217 of file main.c.
References Error_Handler().
Referenced by main().
Variable Documentation
adc1_APPS1
uint16_t adc1_APPS1
Definition at line 64 of file main.c.
Referenced by HAL_ADC_ConvCpltCallback(), HAL_ADC_LevelOutOfWindowCallback(), main(), and StartDrivingLoop().
adc1_APPS2
uint16_t adc1_APPS2
Definition at line 65 of file main.c.
Referenced by HAL_ADC_ConvCpltCallback(), HAL_ADC_LevelOutOfWindowCallback(), main(), and StartDrivingLoop().
adc1_BPS1
uint16_t adc1_BPS1
Definition at line 66 of file main.c.
Referenced by HAL_ADC_ConvCpltCallback(), and StartDrivingLoop().
adc1_BPS2
uint16_t adc1_BPS2
Definition at line 67 of file main.c.
Referenced by HAL_ADC_ConvCpltCallback(), and StartDrivingLoop().
adc2_CoolantFlow
uint16_t adc2_CoolantFlow
Definition at line 71 of file main.c.
Referenced by HAL_ADC_ConvCpltCallback().
adc2_CoolantTemp
uint16_t adc2_CoolantTemp
Definition at line 70 of file main.c.
Referenced by HAL_ADC_ConvCpltCallback().
adc_buf1
volatile uint32_t adc_buf1[ADC1_BUF_LEN]
Definition at line 62 of file main.c.
Referenced by HAL_ADC_ConvCpltCallback().
adc_buf2
volatile uint32_t adc_buf2[ADC2_BUF_LEN]
Definition at line 69 of file main.c.
Referenced by HAL_ADC_ConvCpltCallback(), and HAL_TIM_PeriodElapsedCallback().