EVRTOSProject: Core/Inc/motor_controller.h File Reference
motor_controller.h File Reference
#include "main.h"
#include "uvfr_utils.h"
#include "uvfr_settings.h"
Data Structures
struct motor_controllor_settings
Macros
#define DEFAULT_MOTOR_CONTROLLER_CAN_TIMEOUT ((uv_timespan_ms)200)
#define SERIAL_NUMBER_REGISTER 0x1A
#define FIRMWARE_VERSION_REGISTER 0x1B
Typedefs
typedef struct motor_controllor_settings motor_controller_settings
Enumerations
enum motor_controller_speed_parameters { N_actual = 0x30, N_set = 0x31, N_cmd = 0x32, N_error = 0x33 }
enum motor_controller_current_parameters { todo1 = 0x69 }
enum motor_controller_motor_constants {
nominal_motor_frequency = 0x05, nominal_motor_voltage = 0x06, power_factor = 0x0e, motor_max_current = 0x4D,
motor_continuous_current = 0x4E, motor_pole_number = 0x4F, motor_kt_constant = 0x87, motor_ke_constant = 0x87,
rated_motor_speed = 0x59, motor_temperature_switch_off_point = 0xA3, stator_leakage_inductance = 0xB1, nominal_magnitizing_current = 0xB2,
motor_magnetising_inductance = 0xB3, rotor_resistance = 0xB4, minimum_magnetising_current = 0xB5, time_constant_rotor = 0xB6,
leakage_inductance_ph_ph = 0xBB, stator_resistance_ph_ph = 0xBC, time_constant_stator = 0xBD
}
enum motor_controller_temperatures {
igbt_temperature = 0x4A, motor_temperature = 0x49, air_temperature = 0x4B, current_derate_temperature = 0x4C,
temp_sensor_pt1 = 0x9C, temp_sensor_pt2 = 0x9D, temp_sensor_pt3 = 0x9E, temp_sensor_pt4 = 0x9F
}
enum motor_controller_measurements { DC_bus_voltage = 0xEB }
enum motor_controller_status_information_errors_warnings {
motor_controller_errors_warnings = 0x8F, eprom_read_error = 1<<8, hardware_fault = 1<<9, rotate_field_enable_not_present_run = 1<<10,
CAN_timeout_error = 1<<11, feedback_signal_error = 1<<12, mains_voltage_min_limit = 1<<13, motor_temp_max_limit = 1<<14,
IGBT_temp_max_limit = 1<<15, mains_voltage_max_limit = 1, critical_AC_current = 1<<1, race_away_detected = 1<<2,
ecode_timeout_error = 1<<3, watchdog_reset = 1<<4, AC_current_offset_fault = 1<<5, internal_hardware_voltage_problem = 1<<6,
bleed_resistor_overload = 1<<7, parameter_conflict_detected = 1<<8, special_CPU_fault = 1<<9, rotate_field_enable_not_present_norun = 1<<10,
auxiliary_voltage_min_limit = 1<<11, feedback_signal_problem = 1<<12, warning_5 = 1<<13, motor_temperature_warning = 1<<14,
IGBT_temperature_warning = 1<<15, Vout_saturation_max_limit = 1, warning_9 = 1<<1, speed_actual_resolution_limit = 1<<2,
check_ecode_ID = 1<<3, tripzone_glitch_detected = 1<<4, ADC_sequencer_problem = 1<<5, ADC_measurement_problem = 1<<6,
bleeder_resistor_warning = 1<<7
}
enum motor_controller_io { todo6969 = 6969 }
enum motor_controller_PI_values {
accelerate_ramp = 0x35, dismantling_ramp = 0xED, recuperation_ramp = 0xC7, proportional_gain = 0x1C,
integral_time_constant = 0x1D, integral_memory_max = 0x2B, proportional_gain_2 = 0xC9, current_feed_forward = 0xCB,
ramp_set_current = 0x25
}
enum motor_controller_repeating_time { none = 0, one_hundred_ms = 0x64 }
enum motor_controller_limp_mode { N_lim = 0x34, N_lim_plus = 0x3F, N_lim_minus = 0x3E }
enum motor_controller_startup { clear_errors = 0x8E, firmware_version = 0x1B }
Functions
void MC_Startup (void *args)
Macro Definition Documentation
DEFAULT_MOTOR_CONTROLLER_CAN_TIMEOUT
#define DEFAULT_MOTOR_CONTROLLER_CAN_TIMEOUT ((uv_timespan_ms)200)
Definition at line 15 of file motor_controller.h.
FIRMWARE_VERSION_REGISTER
#define FIRMWARE_VERSION_REGISTER 0x1B
Definition at line 20 of file motor_controller.h.
SERIAL_NUMBER_REGISTER
#define SERIAL_NUMBER_REGISTER 0x1A
Definition at line 19 of file motor_controller.h.
Typedef Documentation
motor_controller_settings
typedef struct motor_controllor_settings motor_controller_settings
Enumeration Type Documentation
motor_controller_current_parameters
enum motor_controller_current_parameters
Enumerator
todo1
Definition at line 30 of file motor_controller.h.
motor_controller_io
enum motor_controller_io
Enumerator
todo6969
Definition at line 113 of file motor_controller.h.
motor_controller_limp_mode
enum motor_controller_limp_mode
Enumerator
N_lim
N_lim_plus
N_lim_minus
Definition at line 138 of file motor_controller.h.
motor_controller_measurements
enum motor_controller_measurements
Enumerator
DC_bus_voltage
Definition at line 68 of file motor_controller.h.
motor_controller_motor_constants
enum motor_controller_motor_constants
Enumerator
nominal_motor_frequency
nominal_motor_voltage
power_factor
motor_max_current
motor_continuous_current
motor_pole_number
motor_kt_constant
motor_ke_constant
rated_motor_speed
motor_temperature_switch_off_point
stator_leakage_inductance
nominal_magnitizing_current
motor_magnetising_inductance
rotor_resistance
minimum_magnetising_current
time_constant_rotor
leakage_inductance_ph_ph
stator_resistance_ph_ph
time_constant_stator
Definition at line 34 of file motor_controller.h.
motor_controller_PI_values
enum motor_controller_PI_values
Enumerator
accelerate_ramp
dismantling_ramp
recuperation_ramp
proportional_gain
integral_time_constant
integral_memory_max
proportional_gain_2
current_feed_forward
ramp_set_current
Definition at line 117 of file motor_controller.h.
motor_controller_repeating_time
enum motor_controller_repeating_time
Enumerator
none
one_hundred_ms
Definition at line 133 of file motor_controller.h.
motor_controller_speed_parameters
enum motor_controller_speed_parameters
Enumerator
N_actual
N_set
N_cmd
N_error
Definition at line 23 of file motor_controller.h.
motor_controller_startup
enum motor_controller_startup
Enumerator
clear_errors
firmware_version
Definition at line 144 of file motor_controller.h.
motor_controller_status_information_errors_warnings
enum motor_controller_status_information_errors_warnings
Enumerator
motor_controller_errors_warnings
eprom_read_error
hardware_fault
rotate_field_enable_not_present_run
CAN_timeout_error
feedback_signal_error
mains_voltage_min_limit
motor_temp_max_limit
IGBT_temp_max_limit
mains_voltage_max_limit
critical_AC_current
race_away_detected
ecode_timeout_error
watchdog_reset
AC_current_offset_fault
internal_hardware_voltage_problem
bleed_resistor_overload
parameter_conflict_detected
special_CPU_fault
rotate_field_enable_not_present_norun
auxiliary_voltage_min_limit
feedback_signal_problem
warning_5
motor_temperature_warning
IGBT_temperature_warning
Vout_saturation_max_limit
warning_9
speed_actual_resolution_limit
check_ecode_ID
tripzone_glitch_detected
ADC_sequencer_problem
ADC_measurement_problem
bleeder_resistor_warning
Definition at line 73 of file motor_controller.h.
motor_controller_temperatures
enum motor_controller_temperatures
Enumerator
igbt_temperature
motor_temperature
air_temperature
current_derate_temperature
temp_sensor_pt1
temp_sensor_pt2
temp_sensor_pt3
temp_sensor_pt4
Definition at line 57 of file motor_controller.h.
Function Documentation
MC_Startup()
void MC_Startup (void * args)
Initializes the motor controller by performing the following steps:
Verifies the serial number from the motor controller.
Checks the firmware version to ensure compatibility.
Executes a motor spin test at low RPM to validate functionality.
Checks for errors and warnings from the motor controller.
Logs successful initialization if all checks pass.
Definition at line 739 of file motor_controller.c.
References firmware_version, FIRMWARE_VERSION_REGISTER, uv_init_task_args::init_info_queue, MC_Expected_FW_Version, MC_Expected_Serial_Number, MC_Request_Data(), uv_init_task_args::meta_task_handle, MOTOR_CONTROLLER, motor_controller_errors_warnings, MotorControllerErrorHandler(), MotorControllerSpinTest(), Parse_Bamocar_Response(), RxData, SERIAL_NUMBER_REGISTER, uv_init_task_args::specific_args, UV_OK, and WaitFor_CAN_Response().
Referenced by uvInit().