EVRTOSProject: Core/Src/motor_controller.c File Reference
motor_controller.c File Reference
#include "motor_controller.h"
#include "can.h"
#include "main.h"
#include "cmsis_os.h"
#include "pdu.h"
Functions
static uint32_t Parse_Bamocar_Response (uint8_t *data, uint8_t length)
static void MotorControllerErrorHandler (uint8_t *data, uint8_t length)
static uint16_t MotorControllerSpinTest (void)
static bool WaitFor_CAN_Response (void)
void MC_Request_Data (uint8_t RegID)
void MC_Check_Error_Warning (uint8_t Data[])
void MC_Validate ()
void MC_Check_Serial_Number (uint8_t Data[])
void MC_Check_Firmware (uint8_t Data[])
void MC_Startup (void *args)
Variables
QueueHandle_t canRxQueue
QueueHandle_t canTxQueue
const uint32_t MC_Expected_Serial_Number = 0x627E7A01
const uint16_t MC_Expected_FW_Version = 0xDC01
const uint32_t max_motor_speed = 3277
motor_controller_settings mc_default_settings
Function Documentation
MC_Check_Error_Warning()
void MC_Check_Error_Warning (uint8_t Data[])
Definition at line 591 of file motor_controller.c.
References AC_current_offset_fault, ADC_measurement_problem, ADC_sequencer_problem, auxiliary_voltage_min_limit, bleed_resistor_overload, bleeder_resistor_warning, CAN_timeout_error, check_ecode_ID, critical_AC_current, ecode_timeout_error, eprom_read_error, feedback_signal_error, feedback_signal_problem, hardware_fault, IGBT_temp_max_limit, IGBT_temperature_warning, internal_hardware_voltage_problem, mains_voltage_max_limit, mains_voltage_min_limit, motor_temp_max_limit, motor_temperature_warning, parameter_conflict_detected, race_away_detected, rotate_field_enable_not_present_norun, rotate_field_enable_not_present_run, special_CPU_fault, speed_actual_resolution_limit, tripzone_glitch_detected, Vout_saturation_max_limit, warning_5, warning_9, and watchdog_reset.
MC_Check_Firmware()
void MC_Check_Firmware (uint8_t Data[])
Definition at line 725 of file motor_controller.c.
MC_Check_Serial_Number()
void MC_Check_Serial_Number (uint8_t Data[])
Definition at line 721 of file motor_controller.c.
MC_Request_Data()
void MC_Request_Data (uint8_t RegID)
Sends a CAN request to the motor controller to retrieve a specific register value. Constructs a CAN message with the specified register ID and sends it via the CAN queue.
Parameters
RegID The ID of the register to request data from.
Definition at line 230 of file motor_controller.c.
References motor_controllor_settings::can_id_tx, hcan2, mc_default_settings, and TxMailbox.
Referenced by MC_Startup(), and MotorControllerSpinTest().
MC_Startup()
void MC_Startup (void * args)
Initializes the motor controller by performing the following steps:
Verifies the serial number from the motor controller.
Checks the firmware version to ensure compatibility.
Executes a motor spin test at low RPM to validate functionality.
Checks for errors and warnings from the motor controller.
Logs successful initialization if all checks pass.
Definition at line 739 of file motor_controller.c.
References firmware_version, FIRMWARE_VERSION_REGISTER, uv_init_task_args::init_info_queue, MC_Expected_FW_Version, MC_Expected_Serial_Number, MC_Request_Data(), uv_init_task_args::meta_task_handle, MOTOR_CONTROLLER, motor_controller_errors_warnings, MotorControllerErrorHandler(), MotorControllerSpinTest(), Parse_Bamocar_Response(), RxData, SERIAL_NUMBER_REGISTER, uv_init_task_args::specific_args, UV_OK, and WaitFor_CAN_Response().
Referenced by uvInit().
MC_Validate()
void MC_Validate ()
Definition at line 717 of file motor_controller.c.
MotorControllerErrorHandler()
static void MotorControllerErrorHandler (uint8_t * data, uint8_t length) static
Processes error and warning information from the motor controller.
Extracts error and warning flags from the CAN message payload.
Logs or triggers a panic if critical errors are detected.
Parameters
data Pointer to the CAN message payload.
length Length of the data payload.
Definition at line 119 of file motor_controller.c.
References AC_current_offset_fault, ADC_measurement_problem, ADC_sequencer_problem, auxiliary_voltage_min_limit, bleed_resistor_overload, bleeder_resistor_warning, CAN_timeout_error, check_ecode_ID, critical_AC_current, ecode_timeout_error, eprom_read_error, feedback_signal_error, feedback_signal_problem, hardware_fault, IGBT_temp_max_limit, IGBT_temperature_warning, internal_hardware_voltage_problem, mains_voltage_max_limit, mains_voltage_min_limit, motor_temp_max_limit, motor_temperature_warning, parameter_conflict_detected, race_away_detected, rotate_field_enable_not_present_norun, rotate_field_enable_not_present_run, special_CPU_fault, speed_actual_resolution_limit, tripzone_glitch_detected, Vout_saturation_max_limit, warning_5, warning_9, and watchdog_reset.
Referenced by MC_Startup().
MotorControllerSpinTest()
static uint16_t MotorControllerSpinTest (void) static
Commands the motor to spin at a low RPM and validates the motor's response:
Sends a spin command via CAN.
Waits for the motor to reach the desired speed.
Checks the actual speed from the motor controller.
Stops the motor after validation.
Returns
0 if the test is successful, 1 for timeout, or 2 for insufficient speed.
Definition at line 62 of file motor_controller.c.
References motor_controllor_settings::can_id_tx, hcan2, mc_default_settings, MC_Request_Data(), N_actual, N_set, RxData, TxMailbox, and WaitFor_CAN_Response().
Referenced by MC_Startup().
Parse_Bamocar_Response()
static uint32_t Parse_Bamocar_Response (uint8_t * data, uint8_t length) static
Parses a 32-bit response value from a Bamocar CAN message. Combines the four bytes of the payload into a single 32-bit integer.
Parameters
data Pointer to the CAN message payload.
length Length of the data payload (expected to be 4 bytes).
Returns
Parsed 32-bit value.
Definition at line 107 of file motor_controller.c.
Referenced by MC_Startup().
WaitFor_CAN_Response()
static bool WaitFor_CAN_Response (void) static
Waits for a CAN response from the motor controller. Uses an RTOS semaphore to synchronize and check if a response is received within the timeout period.
Returns
True if a response is received, otherwise false.
Definition at line 257 of file motor_controller.c.
Referenced by MC_Startup(), and MotorControllerSpinTest().
Variable Documentation
canRxQueue
QueueHandle_t canRxQueue
canTxQueue
QueueHandle_t canTxQueue
max_motor_speed
const uint32_t max_motor_speed = 3277
Definition at line 21 of file motor_controller.c.
mc_default_settings
motor_controller_settings mc_default_settings
Initial value:
= {
    .can_id_tx = 0x200,
    .can_id_rx = 0x201,
    .mc_CAN_timeout = 2,
    .proportional_gain = 10,
    .integral_time_constant = 400,
    .integral_memory_max = 0.6
}
Definition at line 26 of file motor_controller.c.
Referenced by MC_Request_Data(), and MotorControllerSpinTest().
MC_Expected_FW_Version
const uint16_t MC_Expected_FW_Version = 0xDC01
Definition at line 20 of file motor_controller.c.
Referenced by MC_Startup().
MC_Expected_Serial_Number
const uint32_t MC_Expected_Serial_Number = 0x627E7A01
Definition at line 19 of file motor_controller.c.
Referenced by MC_Startup().