EVRTOSProject: Core/Src/pdu.c File Reference
pdu.c File Reference
#include "pdu.h"
#include "can.h"
#include "main.h"
#include "constants.h"
Functions
void PDU_speaker_chirp ()
void PDU_enable_brake_light ()
void PDU_disable_brake_light ()
void PDU_enable_motor_controller ()
void PDU_disable_motor_controller ()
void PDU_enable_shutdown_circuit ()
void PDU_disable_shutdown_circuit ()
void PDU_enable_cooling_fans ()
void PDU_disable_cooling_fans ()
void PDU_enable_coolant_pump ()
void PDU_disable_coolant_pump ()
void initPDU (void *args)
Function Documentation
initPDU()
void initPDU (void * args)
Definition at line 183 of file pdu.c.
References uv_init_task_args::init_info_queue, uv_init_task_args::meta_task_handle, PDU, and UV_OK.
Referenced by uvInit().
PDU_disable_brake_light()
void PDU_disable_brake_light ()
Definition at line 48 of file pdu.c.
References disable_brake_light_msg, Error_Handler(), hcan2, PDU_CAN_ID_Tx, TxData, TxHeader, and TxMailbox.
PDU_disable_coolant_pump()
void PDU_disable_coolant_pump ()
Definition at line 170 of file pdu.c.
References disable_coolant_pump_msg, Error_Handler(), hcan2, PDU_CAN_ID_Tx, TxData, TxHeader, and TxMailbox.
PDU_disable_cooling_fans()
void PDU_disable_cooling_fans ()
Definition at line 136 of file pdu.c.
References disable_left_cooling_fan_msg, disable_right_cooling_fan_msg, Error_Handler(), hcan2, PDU_CAN_ID_Tx, TxData, TxHeader, and TxMailbox.
PDU_disable_motor_controller()
void PDU_disable_motor_controller ()
Definition at line 74 of file pdu.c.
References disable_motor_controller_msg, Error_Handler(), hcan2, PDU_CAN_ID_Tx, TxData, TxHeader, and TxMailbox.
PDU_disable_shutdown_circuit()
void PDU_disable_shutdown_circuit ()
Definition at line 100 of file pdu.c.
References disable_shutdown_circuit_msg, Error_Handler(), hcan2, PDU_CAN_ID_Tx, TxData, TxHeader, and TxMailbox.
PDU_enable_brake_light()
void PDU_enable_brake_light ()
Definition at line 34 of file pdu.c.
References enable_brake_light_msg, Error_Handler(), hcan2, PDU_CAN_ID_Tx, TxData, TxHeader, and TxMailbox.
PDU_enable_coolant_pump()
void PDU_enable_coolant_pump ()
Definition at line 158 of file pdu.c.
References enable_coolant_pump_msg, Error_Handler(), hcan2, PDU_CAN_ID_Tx, TxData, TxHeader, and TxMailbox.
PDU_enable_cooling_fans()
void PDU_enable_cooling_fans ()
Definition at line 115 of file pdu.c.
References enable_left_cooling_fan_msg, enable_right_cooling_fan_msg, Error_Handler(), hcan2, PDU_CAN_ID_Tx, TxData, TxHeader, and TxMailbox.
PDU_enable_motor_controller()
void PDU_enable_motor_controller ()
Definition at line 62 of file pdu.c.
References enable_motor_controller_msg, Error_Handler(), hcan2, PDU_CAN_ID_Tx, TxData, TxHeader, and TxMailbox.
PDU_enable_shutdown_circuit()
void PDU_enable_shutdown_circuit ()
Definition at line 87 of file pdu.c.
References enable_shutdown_circuit_msg, Error_Handler(), hcan2, PDU_CAN_ID_Tx, TxData, TxHeader, and TxMailbox.
PDU_speaker_chirp()
void PDU_speaker_chirp ()
Definition at line 11 of file pdu.c.
References disable_speaker_msg, enable_speaker_msg, Error_Handler(), hcan2, PDU_CAN_ID_Tx, TxData, TxHeader, and TxMailbox.