EVRTOSProject: Core/Inc/rb_tree.h File Reference
rb_tree.h File Reference
Data Structures
struct rbnode
Node of a Red-Black binary search tree.
struct rbtree
struct representing a binary search tree
Macros
#define RB_DUP 1
#define RB_MIN 1
#define RED 0
#define BLACK 1
#define RB_ROOT(rbt) (&(rbt)->root)
#define RB_NIL(rbt) (&(rbt)->nil)
#define RB_FIRST(rbt) ((rbt)->root.left)
#define RB_MINIMAL(rbt) ((rbt)->min)
#define RB_ISEMPTY(rbt) ((rbt)->root.left == &(rbt)->nil && (rbt)->root.right == &(rbt)->nil)
#define RB_APPLY(rbt, f, c, o) rbapply_node((rbt), (rbt)->root.left, (f), (c), (o))
Typedefs
typedef struct rbnode rbnode
Node of a Red-Black binary search tree.
Enumerations
enum rbtraversal { PREORDER, INORDER, POSTORDER }
Evil traversal method specifier for traversing the tree.
Functions
rbtree * rbCreate (int(*compare_func)(const void *, const void *), void(*destroy_func)(void *))
Create and initialize a binary search tree.
void rbDestroy (rbtree *rbt)
Destroy the tree, and de-allocate it's elements.
rbnode * rbFind (rbtree *rbt, void *data)
Find a node of the tree based off the data you provide the tree.
rbnode * rbSuccessor (rbtree *rbt, rbnode *node)
int rbApplyNode (rbtree *rbt, rbnode *node, int(*func)(void *, void *), void *cookie, enum rbtraversal order)
void rbPrint (rbtree *rbt, void(*print_func)(void *))
Function used to print the contents of the tree.
rbnode * rbInsert (rbtree *rbt, void *data)
Function that inserts data into the tree, and creates a new node.
void * rbDelete (rbtree *rbt, rbnode *node, int keep)
Deletes a node from the tree.
int rbCheckOrder (rbtree *rbt, void *min, void *max)
Function that validates that the order of the nodes in the tree is correct.
int rbCheckBlackHeight (rbtree *rbt)
Function that Checks the height of black nodes.
Macro Definition Documentation
BLACK
#define BLACK 1
Definition at line 13 of file rb_tree.h.
RB_APPLY
#define RB_APPLY (rbt, f, c, o) rbapply_node((rbt), (rbt)->root.left, (f), (c), (o))
Definition at line 63 of file rb_tree.h.
RB_DUP
#define RB_DUP 1
Definition at line 9 of file rb_tree.h.
RB_FIRST
#define RB_FIRST (rbt) ((rbt)->root.left)
Definition at line 59 of file rb_tree.h.
RB_ISEMPTY
#define RB_ISEMPTY (rbt) ((rbt)->root.left == &(rbt)->nil && (rbt)->root.right == &(rbt)->nil)
Definition at line 62 of file rb_tree.h.
RB_MIN
#define RB_MIN 1
Definition at line 10 of file rb_tree.h.
RB_MINIMAL
#define RB_MINIMAL (rbt) ((rbt)->min)
Definition at line 60 of file rb_tree.h.
RB_NIL
#define RB_NIL (rbt) (&(rbt)->nil)
Definition at line 58 of file rb_tree.h.
RB_ROOT
#define RB_ROOT (rbt) (&(rbt)->root)
Definition at line 57 of file rb_tree.h.
RED
#define RED 0
Definition at line 12 of file rb_tree.h.
Typedef Documentation
rbnode
typedef struct rbnode rbnode
Node of a Red-Black binary search tree.
Enumeration Type Documentation
rbtraversal
enum rbtraversal
Evil traversal method specifier for traversing the tree.
Function that applies some function to a subtree.
Parameters
rbt Pointer to an the rbtree you wish to apply the functions to
node Pointer to the node that is the root of the tree you wish to apply functions to. This can be a subtree of another tree if needed
func The function you would like to apply to the nodes. This takes in two parameters. The first is a pointer to the data of the node. The second parameter is a pointer to the shared cookie, which allows information to be preserved between different calls to func. This function returns an integer value, with 0 being ok, and the others being various error states.
cookie This is a pointer to some space in memory that all of the calls to @func share, to preserve information.
order This is a member of that specifies the order in which the tree will be traversed.
Attention
DANGER!! RECURSION!! Beware of stack memory usage, since most tasks are memory limited.
Enumerator
PREORDER
INORDER
POSTORDER
Definition at line 18 of file rb_tree.h.
Function Documentation
rbApplyNode()
int rbApplyNode (rbtree * rbt, rbnode * node, int(*)(void *, void *) func, void * cookie, enum rbtraversal order)
Definition at line 116 of file rb_tree.c.
References rbnode::data, INORDER, rbnode::left, POSTORDER, PREORDER, RB_NIL, and rbnode::right.
rbCheckBlackHeight()
int rbCheckBlackHeight (rbtree * rbt)
Function that Checks the height of black nodes.
Attention
DANGER!! THIS FUNCTION IS RECURSIVE. This is intended to be used in a laptop debugging context. The VCU simply does not have enough memory to deal with recursion of this manner.
Deprecated:
Leftovers from laptop unit tests.
Definition at line 571 of file rb_tree.c.
References checkBlackHeight(), RB_FIRST, RB_NIL, RB_ROOT, and RED.
Referenced by rbPrint().
rbCheckOrder()
int rbCheckOrder (rbtree * rbt, void * min, void * max)
Function that validates that the order of the nodes in the tree is correct.
Attention
DANGER!! THIS FUNCTION IS RECURSIVE. This is intended to be used in a laptop debugging context. The VCU simply does not have enough memory to deal with recursion of this manner.
Deprecated:
Leftovers from laptop unit tests.
Definition at line 545 of file rb_tree.c.
References checkOrder(), and RB_FIRST.
rbCreate()
rbtree* rbCreate (int(*)(const void *, const void *) compare_func, void(*)(void *) destroy_func)
Create and initialize a binary search tree.
Parameters
compare_func A function that compares the data of two nodes. Accepts pointers to the data as parameters
destroy_func The destructor function for the data, for safe disposal of dynamically allocated data
Definition at line 28 of file rb_tree.c.
References BLACK, rbnode::color, rbtree::compare, rbtree::count, rbnode::data, rbtree::destroy, rbnode::left, rbtree::min, rbtree::nil, rbnode::parent, RB_NIL, rbnode::right, and rbtree::root.
rbDelete()
void* rbDelete (rbtree * rbt, rbnode * node, int keep)
Deletes a node from the tree.
Parameters
rbt Instance of a rbtree that we are removing the node from.
node Pointer to the node that we would like to remove
keep If keep is a truthy value, a pointer to the data of the node will be returned. Otherwise, the node and it's data will be destroyed.
Return values
If keep is "true", this will return a pointer to the data held by the deleted node. Otherwise it will return NULL.
Definition at line 360 of file rb_tree.c.
References BLACK, rbnode::color, rbtree::count, rbnode::data, deleteRepair(), rbtree::destroy, rbnode::left, rbtree::min, rbnode::parent, RB_FIRST, RB_NIL, rbSuccessor(), RED, and rbnode::right.
rbDestroy()
void rbDestroy (rbtree * rbt)
Destroy the tree, and de-allocate it's elements.
Definition at line 61 of file rb_tree.c.
References destroyAllNodes(), and RB_FIRST.
rbFind()
rbnode* rbFind (rbtree * rbt, void * data)
Find a node of the tree based off the data you provide the tree.
Parameters
rbt Pointer to the tree in which we would like to find the node.
Return values
Returns a pointer to the node if the node is present in the tree. Otherwise, it will return NULL to indicate the node could not be found.
Definition at line 71 of file rb_tree.c.
References rbtree::compare, rbnode::data, rbnode::left, RB_FIRST, RB_NIL, and rbnode::right.
rbInsert()
rbnode* rbInsert (rbtree * rbt, void * data)
Function that inserts data into the tree, and creates a new node.
Parameters
rbt Instance of a rbtree that we would like to insert data into
data Pointer to the data we wish to insert
Return values
This function returns a pointer to the rbnode that was added. The function will return NULL if the system is out of memory, or is otherwise unable to insert the node.
Definition at line 207 of file rb_tree.c.
References BLACK, rbnode::color, rbtree::compare, rbtree::count, rbnode::data, rbtree::destroy, insertRepair(), rbnode::left, rbtree::min, rbnode::parent, RB_FIRST, RB_MIN, RB_NIL, RB_ROOT, RED, and rbnode::right.
rbPrint()
void rbPrint (rbtree * rbt, void(*)(void *) print_func)
Function used to print the contents of the tree.
Parameters
rbt a pointer to the rbtree you wish to print.
print_func A pointer to a print function specific to the data.
Attention
DANGER!! RECURSION!!
Deprecated:
Leftovers from laptop unit tests. Sorta useless, cause like what are we gonna print to?
Definition at line 607 of file rb_tree.c.
References print(), RB_FIRST, and rbCheckBlackHeight().
rbSuccessor()
rbnode* rbSuccessor (rbtree * rbt, rbnode * node)
Definition at line 92 of file rb_tree.c.
References rbnode::left, rbnode::parent, RB_NIL, RB_ROOT, and rbnode::right.
Referenced by rbDelete().