EVRTOSProject: rbtree Struct Reference
rbtree Struct Reference
struct representing a binary search tree
#include <rb_tree.h>
Data Fields
int(* compare)(const void *, const void *)
void(* print)(void *)
void(* destroy)(void *)
rbnode root
rbnode nil
rbnode * min
int count
Detailed Description
struct representing a binary search tree
Definition at line 39 of file rb_tree.h.
Field Documentation
compare
int(* rbtree::compare) (const void *, const void *)
Function to compare between two different nodes
Definition at line 40 of file rb_tree.h.
Referenced by checkOrder(), rbCreate(), rbFind(), and rbInsert().
count
int rbtree::count
number of items stored in the tree
Definition at line 53 of file rb_tree.h.
Referenced by destroyAllNodes(), rbCreate(), rbDelete(), and rbInsert().
destroy
void(* rbtree::destroy) (void *)
Destructor function for whatever data is stored in the tree
Definition at line 42 of file rb_tree.h.
Referenced by destroyAllNodes(), rbCreate(), rbDelete(), and rbInsert().
min
rbnode* rbtree::min
Pointer to minimum element
Definition at line 50 of file rb_tree.h.
Referenced by rbCreate(), rbDelete(), and rbInsert().
nil
rbnode rbtree::nil
The "NIL" node of the tree, used to avoid fucked null errors
Definition at line 45 of file rb_tree.h.
Referenced by rbCreate().
print
void(* rbtree::print) (void *)
For printing purposes. NOT YET IMPLEMENTED ON ANY SYSTEMS IN THE CAR
Definition at line 41 of file rb_tree.h.
root
rbnode rbtree::root
Root of actual tree
Definition at line 44 of file rb_tree.h.
Referenced by rbCreate().
The documentation for this struct was generated from the following file:
Core/Inc/rb_tree.h