EVRTOSProject: Core/Src/temp_monitoring.c File Reference
temp_monitoring.c File Reference
#include "uvfr_utils.h"
#include "gpio.h"
Functions
uv_status initTempMonitor (void *arguments)
void tempMonitorTask (void *args)
Monitors the temperatures of various points in the tractive system, and activates various cooling systems and such accordingly.
Function Documentation
initTempMonitor()
uv_status initTempMonitor (void * arguments)
Definition at line 12 of file temp_monitoring.c.
References _UV_DEFAULT_TASK_STACK_SIZE, uv_task_info::active_states, uv_task_info::deletion_states, uv_task_info::instances, PROGRAMMING, uv_task_info::stack_size, StartDrivingLoop(), uv_task_info::suspension_states, uv_task_info::task_args, uv_task_info::task_function, uv_task_info::task_name, uv_task_info::task_period, uv_task_info::task_priority, UV_DRIVING, UV_ERROR, UV_ERROR_STATE, UV_LAUNCH_CONTROL, UV_OK, UV_READY, and uvCreateTask().
Referenced by uvInitStateEngine().
tempMonitorTask()
void tempMonitorTask (void * args)
Monitors the temperatures of various points in the tractive system, and activates various cooling systems and such accordingly.
Atm, this is mostly serving as an example of a task
These here lines set the delay. This task executes exactly at the period
Definition at line 53 of file temp_monitoring.c.
References uv_task_info::cmd_data, uv_task_info::task_period, UV_KILL_CMD, and UV_SUSPEND_CMD.