EVRTOSProject: Core/Src/uvfr_state_engine.c File Reference
uvfr_state_engine.c File Reference
#include "uvfr_utils.h"
Data Structures
struct state_change_daemon_args
Macros
#define UVFR_STATE_MACHINE_IMPLIMENTATION
#define MAX_NUM_MANAGED_TASKS 16
#define MAX_NUM_SVC_TASKS 8
Typedefs
typedef struct state_change_daemon_args state_change_daemon_args
Functions
uv_status killEmAll ()
The name should be pretty self explanatory.
uv_task_info * uvCreateTask ()
This function gets called when you want to create a task, and register it with the task register. Theres some gnarlyness here, but not unacceptable levels. Pray this thing doesn't hang itself.
uv_status addTaskToTaskRegister ()
uv_status _uvValidateSpecificTask (uv_task_id id)
uv_status uvValidateManagedTasks ()
ensure that all the tasks people have created actually make sense, and are valid
uv_status uvStartTask (uint32_t *tracker, uv_task_info *t)
: This is a function that starts tasks which are already registered in the system
uv_status uvInitStateEngine ()
Function that prepares the state engine to do its thing.
uv_status uvDeInitStateEngine ()
Stops and frees all resources used by uvfr_state_engine.
uv_status uvStartStateMachine ()
static uv_status uvKillTaskViolently (uv_task_info *t)
if a task refuses to comply with the SCD, then it has no choice but to be deleted. There is nothing that can be done.
uv_status uvDeleteTask (uint32_t *tracker, uv_task_info *t)
deletes a managed task via the system
uv_status uvSuspendTask (uint32_t *tracker, uv_task_info *t)
function to suspend one of the managed tasks
uv_status changeVehicleState (uint16_t state)
Function for changing the state of the vehicle, as well as the list of active + inactive tasks.
void __uvPanic (char *msg, uint8_t msg_len, const char *file, const int line, const char *func)
Something bad has occurred here now we in trouble.
void killSelf (uv_task_info *t)
This function is called by a task to nuke itself. Is a wrapper function that is used to do all the different things.
void suspendSelf (uv_task_info *t)
Called by a task that needs to suspend itself, once the task has determined it is safe to do so.
static uv_status proccessSCDMsg (uv_scd_response *msg)
Helper function for the SCD, that proccesses a message, and double checks to make sure the task that sent the message isn't straight up lying to us.
void _stateChangeDaemon (void *args)
This collects all the data changing from different tasks, and makes sure that everything works properly.
uvPanic ("SCD Timeout", 0)
uvFree (args)
void uvTaskManager (void *args)
The big papa task that deals with handling all of the others.
uv_task_info * uvCreateServiceTask ()
Create a new service task, because fuck you, thats why.
uv_status uvStartSVCTask ()
Function to start a service task specifically.
uv_status uvSuspendSVCTask ()
Function that suspends a service task.
uv_status uvDeleteSVCTask ()
For when you need to delete a service task... for some reason...
uv_status uvRestartSVCTask (uv_task_info *t)
Function that takes a service part that may be messed up and tries to reboot it to recover.
void uvSVCTaskManager (void *args)
oversees all of the service tasks, and makes sure that theyre alright
uv_task_id getSVCTaskID (char *tsk_name)
Variables
static uv_task_id _next_task_id = 0
static uv_task_info * _task_register = NULL
static uv_task_id _next_svc_task_id = 0
static uv_task_info * _svc_task_register = NULL
static volatile bool SCD_active = false
static QueueHandle_t state_change_queue = NULL
enum uv_vehicle_state_t vehicle_state = UV_BOOT
enum uv_vehicle_state_t previous_state = UV_BOOT
END_OF_STATE_CHANGE_DAEMON __pad0__
Macro Definition Documentation
MAX_NUM_MANAGED_TASKS
#define MAX_NUM_MANAGED_TASKS 16
Definition at line 13 of file uvfr_state_engine.c.
MAX_NUM_SVC_TASKS
#define MAX_NUM_SVC_TASKS 8
Definition at line 14 of file uvfr_state_engine.c.
UVFR_STATE_MACHINE_IMPLIMENTATION
#define UVFR_STATE_MACHINE_IMPLIMENTATION
Definition at line 8 of file uvfr_state_engine.c.
Typedef Documentation
state_change_daemon_args
typedef struct state_change_daemon_args state_change_daemon_args
Function Documentation
__uvPanic()
void __uvPanic (char * msg, uint8_t msg_len, const char * file, const int line, const char * func)
Something bad has occurred here now we in trouble.
Definition at line 482 of file uvfr_state_engine.c.
_stateChangeDaemon()
void _stateChangeDaemon (void * args)
This collects all the data changing from different tasks, and makes sure that everything works properly.
Attention
DO NOT EVER JUST CALL THIS FUNCTION. THIS SHOULD ONLY BE CALLED FROM changeVehicleState
Parameters
This accepts a void* pointer to avoid compile errors with freeRTOS, since freeRTOS expects a pointer to the function that accepts a void pointer
This is a one-shot RTOS task that spawns in when we want to change the state of the vehicle state. It performs this in the following way
We get to iterate through all of the managed tasks. Goes via IDs as well. We load up the array entry as a temp pointer to a task info struct. As we go through it determines what to do by comparing the uv_task_info.active_states as well as uv_task_info.deletion_states and uv_task_info.suspension_states with uv_vehicle_state
This is done with the bitwise & operator, since the definition of the uv_vehicle_state_t enum facilitates this by only using factors of two.
Acquires pointer to task definition struct, then sets the queue in the struct to the SCD queue, so that the task actually does task things. Love when that happens. Next it sets the bit in the task_tracker corresponding to the task id, therefore marking that some action must be taken to either
confirm that no action is neccessary
bring the task state into the correct state
 */
        tmp_task = &(_task_register[i]);
        task_tracker |= 0x01<<i;
        //tmp_task->manager = incoming_scd_msg; //No longer using this var, instead using the state_change_queue static global var
//      if(((tmp_task->task_flags)&(UV_TASK_MANAGER_MASK | UV_TASK_SCD_IGNORE)) == UV_TASK_VEHICLE_APPLICATION){
//          task_tracker |= 0x01<<i;
//      }else{
//          //If we get here that means that either:
//          //This task has the SCD ignore flag active
//          //This is a SVC task
//          continue; //This is not the task you want
//      }
        //redundant_tracker |= 0x01<<i;
        /**
Now we suspend the task because it has been misbehaving in school
Wait for all the tasks that had changes made to respond.
 */
    uv_scd_response* response = NULL;
    for(int i = 0; i < _LONGEST_SC_TIME/_SC_DAEMON_PERIOD; i++){
        vTaskDelay(_SC_DAEMON_PERIOD);
        for(int j = 0; j<10;j++){
            if(xQueueReceive(state_change_queue,&response,1) == pdPASS){
                if(response == NULL){//definately not supposed to happen
                    uvPanic("null scd response",0);
                }
                if(proccessSCDMsg(response)==UV_OK){
//                  if(task_tracker & 0xFFFFFFF0){
//                                  //gotcha
//                      uvPanic("gotcha bitch proccessSCDMsg!!",0);
//                  }
                    //has_task_succeeded |= (0x01<<response->meta_id);
                    task_tracker &= ~(0x01<<response->meta_id);
                    if (_task_register[response->meta_id].task_state == UV_TASK_DELETED){
                        _task_register[response->meta_id].task_handle = NULL;
                    }
                }else{
                    //Not ok, this means that process SCD has returned something weird. More detailed error_handling can be added later.
                    uvPanic("Task giving Sass to SCD",0);
                }
                if(uvFree(response)!=UV_OK){
                    uvPanic("failed to free memory", 0);
                }
                response = NULL;
            }else{
                break;
            }
        }
If this is 0, then that means that all the tasks have successfully had their states validated.
This means we can just exit and we're chillin.
Definition at line 657 of file uvfr_state_engine.c.
References _LONGEST_SC_TIME, _next_task_id, _SC_DAEMON_PERIOD, _task_register, uv_task_info::active_states, uv_task_info::deletion_states, uv_scd_response::meta_id, proccessSCDMsg(), SCD_active, state_change_queue, uv_task_info::suspension_states, uv_task_info::task_handle, uv_task_info::task_state, UV_OK, UV_TASK_DELETED, UV_TASK_NOT_STARTED, UV_TASK_RUNNING, UV_TASK_SUSPENDED, uvDeleteTask(), uvFree(), uvPanic(), uvStartTask(), uvSuspendTask(), and vehicle_state.
Referenced by changeVehicleState().
_uvValidateSpecificTask()
uv_status _uvValidateSpecificTask (uv_task_id id)
Definition at line 83 of file uvfr_state_engine.c.
References _task_register, uv_task_info::active_states, uv_task_info::deletion_states, uv_task_info::max_instances, uv_task_info::suspension_states, uv_task_info::task_function, uv_task_info::task_name, UV_ERROR, and UV_OK.
Referenced by uvValidateManagedTasks().
addTaskToTaskRegister()
uv_status addTaskToTaskRegister ()
Definition at line 79 of file uvfr_state_engine.c.
changeVehicleState()
uv_status changeVehicleState (uint16_t state)
Function for changing the state of the vehicle, as well as the list of active + inactive tasks.
This function also changes out the tasks that are executing, by invoking the legendary state_change_daemon
If the state we wish to change to is the same as the state we're in, then no need to be executing any of this fancy code
Transition from UV_INIT to UV_READY states
Transition from UV_INIT to UV_ERROR states
Definition at line 426 of file uvfr_state_engine.c.
References _stateChangeDaemon(), state_change_daemon_args::meta_task_handle, previous_state, UV_ABORTED, UV_BOOT, UV_DRIVING, UV_ERROR_STATE, UV_INIT, UV_LAUNCH_CONTROL, UV_OK, UV_READY, uvFree(), uvPanic(), and vehicle_state.
Referenced by daqMasterTask(), and uvInit().
getSVCTaskID()
uv_task_id getSVCTaskID (char * tsk_name)
Sometimes you just gottta deal with it lol
Definition at line 985 of file uvfr_state_engine.c.
killEmAll()
uv_status killEmAll ()
The name should be pretty self explanatory.
Definition at line 266 of file uvfr_state_engine.c.
References _BV_32, _next_task_id, _task_register, UV_ERROR, UV_OK, and uvDeleteTask().
Referenced by uvDeInitStateEngine().
killSelf()
void killSelf (uv_task_info * t)
This function is called by a task to nuke itself. Is a wrapper function that is used to do all the different things.
First lets load up the queue and the values in it. These come from the task we are doing.
Definition at line 496 of file uvfr_state_engine.c.
References uv_task_info::cmd_data, uv_scd_response::meta_id, uv_scd_response::response_val, state_change_queue, uv_task_info::task_handle, uv_task_info::task_id, uv_task_info::task_state, UV_NO_CMD, UV_SUCCESSFUL_DELETION, UV_TASK_DELETED, uvFree(), and uvPanic().
Referenced by daqMasterTask(), odometerTask(), StartDrivingLoop(), and tempMonitorTask().
proccessSCDMsg()
static uv_status proccessSCDMsg (uv_scd_response * msg) static
Helper function for the SCD, that proccesses a message, and double checks to make sure the task that sent the message isn't straight up lying to us.
This function is responsible for the following functionality:
Make sure that the message claims that the deletion or suspension of a task is successful
If a task claims that it is deleted, or suspended, then we must verify that this is the case
Get the id of the message, then use that to index the _task_register
Definition at line 589 of file uvfr_state_engine.c.
References _task_register, uv_scd_response::meta_id, uv_scd_response::response_val, uv_task_info::task_handle, uv_task_info::task_state, UV_COULDNT_DELETE, UV_COULDNT_SUSPEND, UV_ERROR, UV_OK, UV_SUCCESSFUL_DELETION, UV_SUCCESSFUL_SUSPENSION, UV_TASK_DELETED, and UV_UNSAFE_STATE.
Referenced by _stateChangeDaemon().
suspendSelf()
void suspendSelf (uv_task_info * t)
Called by a task that needs to suspend itself, once the task has determined it is safe to do so.
Definition at line 546 of file uvfr_state_engine.c.
References uv_task_info::cmd_data, uv_scd_response::meta_id, uv_scd_response::response_val, state_change_queue, uv_task_info::task_handle, uv_task_info::task_id, uv_task_info::task_state, UV_NO_CMD, UV_SUCCESSFUL_SUSPENSION, UV_TASK_SUSPENDED, uvFree(), and uvPanic().
Referenced by daqMasterTask(), odometerTask(), StartDrivingLoop(), and tempMonitorTask().
uvCreateServiceTask()
uv_task_info* uvCreateServiceTask ()
Create a new service task, because fuck you, thats why.
Acquire the pointer to the spot in the array, we are doing this since we need to return the pointer anyways, and it cleans up the syntax a little.
Definition at line 848 of file uvfr_state_engine.c.
References _next_svc_task_id, _task_register, _UV_DEFAULT_TASK_INSTANCES, _UV_DEFAULT_TASK_STACK_SIZE, uv_task_info::active_states, uv_task_info::deletion_states, uv_task_info::max_instances, MAX_NUM_MANAGED_TASKS, uv_task_info::next, uv_task_info::stack_size, uv_task_info::suspension_states, uv_task_info::task_function, uv_task_info::task_handle, uv_task_info::task_id, uv_task_info::task_name, uv_task_info::task_priority, uv_task_info::task_state, and UV_TASK_NOT_STARTED.
Referenced by uvSVCTaskManager().
uvCreateTask()
uv_task_info* uvCreateTask ()
This function gets called when you want to create a task, and register it with the task register. Theres some gnarlyness here, but not unacceptable levels. Pray this thing doesn't hang itself.
Do not exceed the number of tasks available
Acquire the pointer to the spot in the array, we are doing this since we need to return the pointer anyways, and it cleans up the syntax a little.
Definition at line 40 of file uvfr_state_engine.c.
References _next_task_id, _task_register, _UV_DEFAULT_TASK_INSTANCES, _UV_DEFAULT_TASK_STACK_SIZE, uv_task_info::active_states, uv_task_info::deletion_states, uv_task_info::max_instances, MAX_NUM_MANAGED_TASKS, uv_task_info::next, uv_task_info::stack_size, uv_task_info::suspension_states, uv_task_info::task_function, uv_task_info::task_handle, uv_task_info::task_id, uv_task_info::task_name, uv_task_info::task_priority, uv_task_info::task_state, and UV_TASK_NOT_STARTED.
Referenced by initDaqTask(), initDrivingLoop(), initOdometer(), and initTempMonitor().
uvDeInitStateEngine()
uv_status uvDeInitStateEngine ()
Stops and frees all resources used by uvfr_state_engine.
If we need to initialize the state engine, gotta de-initialize as well
Definition at line 223 of file uvfr_state_engine.c.
References killEmAll().
uvDeleteSVCTask()
uv_status uvDeleteSVCTask ()
For when you need to delete a service task... for some reason...
Definition at line 902 of file uvfr_state_engine.c.
References UV_OK.
uvDeleteTask()
uv_status uvDeleteTask (uint32_t * tracker, uv_task_info * t)
deletes a managed task via the system
This function is the lowtier god of the program. It pulls up and is like "YOU SHOULD KILL YOURSELF, NOW!!" It sends a message to the task which tells it to kill itself.
This checks with the RTOS kernel to see that the task as stated by the scheduler matches the state known by uvfr_utils
if we have reached this point in the function, then the task is active and ready to get nuked
Definition at line 309 of file uvfr_state_engine.c.
References uv_task_info::cmd_data, uv_task_info::task_handle, uv_task_info::task_id, uv_task_info::task_state, UV_ABORTED, UV_ERROR, UV_KILL_CMD, UV_OK, UV_TASK_DELETED, UV_TASK_NOT_STARTED, UV_TASK_SUSPENDED, and uvPanic().
Referenced by _stateChangeDaemon(), and killEmAll().
uvFree()
uvFree (args)
Referenced by _stateChangeDaemon(), changeVehicleState(), killSelf(), nukeSettings(), suspendSelf(), uvInit(), and uvSVCTaskManager().
uvInitStateEngine()
uv_status uvInitStateEngine ()
Function that prepares the state engine to do its thing.
Who even fucking knows at this point
Definition at line 202 of file uvfr_state_engine.c.
References __uvInitPanic(), _task_register, initDaqTask(), initDrivingLoop(), initOdometer(), initTempMonitor(), MAX_NUM_MANAGED_TASKS, and UV_OK.
Referenced by uvInit().
uvKillTaskViolently()
static uv_status uvKillTaskViolently (uv_task_info * t) static
if a task refuses to comply with the SCD, then it has no choice but to be deleted. There is nothing that can be done.
You will not win against the operating system.
The first thing that needs to happen, is we will tell the kernel to release any resources owned by the task.
Definition at line 287 of file uvfr_state_engine.c.
References UV_OK, and uvPanic().
Referenced by uvRestartSVCTask().
uvPanic()
uvPanic ("SCD Timeout" , 0)
Referenced by __uvMallocOS(), _stateChangeDaemon(), CANbusTxSvcDaemon(), changeVehicleState(), handleCANbusError(), initIMD(), initPDU(), killSelf(), MC_Startup(), suspendSelf(), uvDeleteTask(), uvInit(), uvKillTaskViolently(), and uvSuspendTask().
uvRestartSVCTask()
uv_status uvRestartSVCTask (uv_task_info * t)
Function that takes a service part that may be messed up and tries to reboot it to recover.
This may be neccessary if a SVC task is not responding. Be careful though, since this has the potential to delay more important tasks :o Therefore, this technique should be used sparingly, and each task gets a limited number of attempts within a certain time period.
Definition at line 912 of file uvfr_state_engine.c.
References UV_OK, uvKillTaskViolently(), and uvStartSVCTask().
uvStartStateMachine()
uv_status uvStartStateMachine ()
Actually starts up the state engine to do state engine things
Definition at line 233 of file uvfr_state_engine.c.
References previous_state, UV_ERROR, UV_INIT, UV_OK, uvValidateManagedTasks(), and vehicle_state.
Referenced by uvInit().
uvStartSVCTask()
uv_status uvStartSVCTask ()
Function to start a service task specifically.
Definition at line 886 of file uvfr_state_engine.c.
References UV_OK.
Referenced by uvRestartSVCTask().
uvStartTask()
uv_status uvStartTask (uint32_t * tracker, uv_task_info * t)
: This is a function that starts tasks which are already registered in the system
This bad boi gets called from the stateChangeDaemon because it's a special little snowflake.
The first thing we will do is check if the task is running, since this could theoretically get called from literally anywhere. If the task is running, then we check to see if t->task_handle is set to NULL . If it is null, that is a physically impossible_state. Neither very mindful or very demure.
That being said, if the task appears legit, then just update the corresponding bits in the tracker, and return that the task has aborted.
If a task has been suspended, we do not want to create a new instance of the task, becuase then the task will go out of scope, and changing the task handle to a new instance will result in the task never being de-initialized, therefore causing a memory leak. We want to call vTaskResume instead, and just boot the task back into existence.
If none of the previous if statements caught the task handle, then that means that either this is our first time attempting to activate this task, or the task has been deleted at some point prior to this one
The function osThreadCreate returns null if it fails to create a thread. If that happens, we really do have a problem, so we will be returning an error value
Definition at line 133 of file uvfr_state_engine.c.
References _BV_32, uv_task_info::stack_size, uv_task_info::task_function, uv_task_info::task_handle, uv_task_info::task_id, uv_task_info::task_name, uv_task_info::task_priority, uv_task_info::task_state, UV_ABORTED, UV_ERROR, UV_OK, UV_TASK_RUNNING, and UV_TASK_SUSPENDED.
Referenced by _stateChangeDaemon(), and uvSVCTaskManager().
uvSuspendSVCTask()
uv_status uvSuspendSVCTask ()
Function that suspends a service task.
Definition at line 895 of file uvfr_state_engine.c.
References UV_OK.
uvSuspendTask()
uv_status uvSuspendTask (uint32_t * tracker, uv_task_info * t)
function to suspend one of the managed tasks
Definition at line 368 of file uvfr_state_engine.c.
References uv_task_info::cmd_data, uv_task_info::task_handle, uv_task_info::task_id, uv_task_info::task_state, UV_ERROR, UV_OK, UV_SUSPEND_CMD, UV_TASK_DELETED, UV_TASK_NOT_STARTED, UV_TASK_SUSPENDED, and uvPanic().
Referenced by _stateChangeDaemon().
uvSVCTaskManager()
void uvSVCTaskManager (void * args)
oversees all of the service tasks, and makes sure that theyre alright
Start all of the service tasks. This involves allocating neccessary memory, setting the appropriate task parameters, and saying "fuck it we ball" and adding the tasks to the central task tracking data structure.
Now we deinitialize the svcTaskManager. This is done by doing the following:
actually shut down the svc tasks
double check that the tasks have acually shut down
if any svc tasks are resisting nature's call, they will be shut down forcibly
deallocate data structures specific to uvSVCTaskManager
Lovely times for all
Definition at line 929 of file uvfr_state_engine.c.
References __uvInitPanic(), _svc_task_register, uv_task_info::active_states, CAN_TX_DAEMON_NAME, CANbusTxSvcDaemon(), MAX_NUM_SVC_TASKS, uv_task_info::task_function, task_management_info::task_handle, uv_task_info::task_name, uvCreateServiceTask(), uvFree(), and uvStartTask().
uvTaskManager()
void uvTaskManager (void * args)
The big papa task that deals with handling all of the others.
This line deletes the queue to free up the memory
 */
vQueueDelete(state_change_queue);
state_change_queue = NULL;
/**
The final act of the SCD, is to delete itself
 */
vTaskDelete(scd_handle);
Definition at line 836 of file uvfr_state_engine.c.
uvValidateManagedTasks()
uv_status uvValidateManagedTasks ()
ensure that all the tasks people have created actually make sense, and are valid
Definition at line 111 of file uvfr_state_engine.c.
References _next_task_id, _uvValidateSpecificTask(), and UV_OK.
Referenced by uvStartStateMachine().
Variable Documentation
__pad0__
END_OF_STATE_CHANGE_DAEMON __pad0__
Definition at line 816 of file uvfr_state_engine.c.
_next_svc_task_id
uv_task_id _next_svc_task_id = 0 static
Definition at line 21 of file uvfr_state_engine.c.
Referenced by uvCreateServiceTask().
_next_task_id
uv_task_id _next_task_id = 0 static
Definition at line 18 of file uvfr_state_engine.c.
Referenced by _stateChangeDaemon(), killEmAll(), uvCreateTask(), and uvValidateManagedTasks().
_svc_task_register
uv_task_info* _svc_task_register = NULL static
Definition at line 22 of file uvfr_state_engine.c.
Referenced by uvSVCTaskManager().
_task_register
uv_task_info* _task_register = NULL static
Definition at line 19 of file uvfr_state_engine.c.
Referenced by _stateChangeDaemon(), _uvValidateSpecificTask(), killEmAll(), proccessSCDMsg(), uvCreateServiceTask(), uvCreateTask(), and uvInitStateEngine().
previous_state
enum uv_vehicle_state_t previous_state = UV_BOOT
Definition at line 29 of file uvfr_state_engine.c.
Referenced by changeVehicleState(), and uvStartStateMachine().
SCD_active
volatile bool SCD_active = false static
Definition at line 25 of file uvfr_state_engine.c.
Referenced by _stateChangeDaemon().
state_change_queue
QueueHandle_t state_change_queue = NULL static
Definition at line 26 of file uvfr_state_engine.c.
Referenced by _stateChangeDaemon(), killSelf(), and suspendSelf().
vehicle_state
enum uv_vehicle_state_t vehicle_state = UV_BOOT
Definition at line 28 of file uvfr_state_engine.c.
Referenced by _stateChangeDaemon(), changeVehicleState(), daqMasterTask(), and uvStartStateMachine().