EVRTOSProject: Core/Inc/uvfr_utils.h File Reference
uvfr_utils.h File Reference
#include "main.h"
#include "cmsis_os.h"
#include "adc.h"
#include "can.h"
#include "dma.h"
#include "tim.h"
#include "gpio.h"
#include "spi.h"
#include "FreeRTOS.h"
#include "task.h"
#include "uvfr_settings.h"
#include "uvfr_state_engine.h"
#include "bms.h"
#include "motor_controller.h"
#include "dash.h"
#include "imd.h"
#include "pdu.h"
#include "daq.h"
#include "oled.h"
#include "driving_loop.h"
#include "temp_monitoring.h"
#include "odometer.h"
#include "FreeRTOSConfig.h"
#include "stdint.h"
#include <stdlib.h>
Data Structures
struct uv_mutex_info
struct uv_binary_semaphore_info
struct uv_semaphore_info
union access_control_info
struct uv_CAN_msg
struct uv_init_struct
struct uv_task_info
This struct is designed to hold neccessary information about an RTOS task that will be managed by uvfr_state_engine.
struct tm_data
struct p_status
struct uv_init_task_args
Struct designed to act like the uv_task_info struct, but for the initialisation tasks. As a result it takes fewer arguments.
struct uv_internal_params
Data used by the uvfr_utils library to do what it needs to do :)
struct uv_init_task_response
Struct representing the response of one of the initialization tasks.
Macros
#define _BV(x) _BV_16(x)
#define _BV_8(x) ((uint8_t)(0x01U >> x))
#define _BV_16(x) ((uint16_t)(0x01U >> x))
#define _BV_32(x) ((uint32_t)(0x01U >> x))
#define endianSwap(x) endianSwap16(x)
#define endianSwap8(x) x
#define endianSwap16(x) (((x & 0x00FF)<<8) | ((x & 0xFF00)>>8))
#define endianSwap32(x) (((x & 0x000000FF)<<16)|((x & 0x0000FF00)<<8)|((x & 0x00FF0000)>>8)|((x & 0xFF000000)>>16))
#define deserializeSmallE16(x, i) ((x[i])|(x[i+1]<<8))
#define deserializeSmallE32(x, i) ((x[i])|(x[i+1]<<8)|(x[i+2]<<16)|(x[i+3]<<24))
#define deserializeBigE16(x, i) ((x[i]<<8)|(x[i+1]))
#define deserializeBigE32(x, i) ((x[i]<<24)|(x[i+1]<<16)|(x[i+2]<<8)|(x[i+3]))
#define serializeSmallE16(x, d, i) x[i]=d&0x00FF; x[i+1]=(d&0xFF00)>>8
#define serializeSmallE32(x, d, i) x[i]=d&0x000000FF; x[i+1]=(d&0x0000FF00)>>8; x[i+2]=(d&0x00FF0000)>>16; x[i+3]=(d&0xFF000000)>>24
#define serializeBigE16(x, d, i) x[i+1]=d&0x00FF; x[i]=(d&0xFF00)>>8
#define serializeBigE32(x, d, i) x[i+3]=d&0x000000FF; x[i+2]=(d&0x0000FF00)>>8; x[i+1]=(d&0x00FF0000)>>16; x[i]=(d&0xFF000000)>>24
#define false 0
#define true !false
#define MAX_INIT_TIME 2500
#define INIT_CHECK_PERIOD 100
#define UV_CAN1
#define UV_CAN2
#define USE_OLED_DEBUG 1
#define UV_CAN_EXTENDED_ID 0x01
#define UV_CAN_CHANNEL_MASK 0b00000110
#define UV_TASK_VEHICLE_APPLICATION 0b00000001
#define UV_TASK_PERIODIC_SVC 0b00000010
#define UV_TASK_DORMANT_SVC 0b00000011
#define UV_TASK_MANAGER_MASK 0b00000011
#define UV_TASK_LOG_START_STOP_TIME 0b00000100
#define UV_TASK_LOG_MEM_USAGE 0b00001000
#define UV_TASK_SCD_IGNORE 0b00010000
Typedefs
typedef uint8_t bool
typedef uint8_t uv_task_id
typedef enum uv_task_cmd_e uv_task_cmd
typedef uint8_t uv_ext_device_id
typedef uint32_t uv_timespan_ms
typedef enum uv_status_t uv_status
This is meant to be a return type from functions that indicates what is actually going on.
typedef enum uv_task_state_t uv_task_status
typedef enum task_priority task_priority
typedef enum access_control_t access_control_type
typedef union access_control_info access_control_info
typedef struct uv_CAN_msg uv_CAN_msg
typedef struct uv_init_struct uv_init_struct
typedef struct uv_task_info uv_task_info
This struct is designed to hold neccessary information about an RTOS task that will be managed by uvfr_state_engine.
typedef struct tm_data task_management_data
typedef struct p_status p_status
typedef struct uv_init_task_args uv_init_task_args
Struct designed to act like the uv_task_info struct, but for the initialisation tasks. As a result it takes fewer arguments.
typedef struct uv_internal_params uv_internal_params
Data used by the uvfr_utils library to do what it needs to do :)
typedef struct uv_init_task_response uv_init_task_response
Struct representing the response of one of the initialization tasks.
Enumerations
enum uv_status_t { UV_OK, UV_WARNING, UV_ERROR, UV_ABORTED }
This is meant to be a return type from functions that indicates what is actually going on.
enum uv_task_state_t { UV_TASK_NOT_STARTED, UV_TASK_DELETED, UV_TASK_RUNNING, UV_TASK_SUSPENDED }
enum task_priority {
IDLE_TASK_PRIORITY, LOW_PRIORITY, BELOW_NORMAL, MEDIUM_PRIORITY,
ABOVE_NORMAL, HIGH_PRIORITY, REALTIME_PRIORITY
}
enum uv_vehicle_state_t {
UV_INIT = 0x0001, UV_READY = 0x0002, PROGRAMMING = 0x0004, UV_DRIVING = 0x0008,
UV_SUSPENDED = 0x0010, UV_LAUNCH_CONTROL = 0x0020, UV_ERROR_STATE = 0x0040, UV_BOOT = 0x0080,
UV_HALT = 0x0100
}
enum uv_driving_mode_t { normal, accel, econ, limp }
enum uv_external_device { MOTOR_CONTROLLER = 0, BMS = 1, IMD = 2, PDU = 3 }
ID for external devices, which allows us to know what's good with them.
enum access_control_t {
UV_NONE, UV_DUMB_FLAG, UV_MUTEX, UV_BINARY_SEMAPHORE,
UV_SEMAPHORE
}
Functions
void uvInit (void *arguments)
: Function that initializes all of the car's stuff.
void __uvInitPanic ()
Low Level Panic, that does not require the full UVFR utils functionality to be operational.
uv_status uvIsPTRValid (void *ptr)
function that checks to make sure a pointer points to a place it is allowed to point to
Variables
uv_internal_params global_context
Macro Definition Documentation
_BV
#define _BV (x) _BV_16(x)
Definition at line 51 of file uvfr_utils.h.
_BV_16
#define _BV_16 (x) ((uint16_t)(0x01U >> x))
Definition at line 53 of file uvfr_utils.h.
_BV_32
#define _BV_32 (x) ((uint32_t)(0x01U >> x))
Definition at line 54 of file uvfr_utils.h.
_BV_8
#define _BV_8 (x) ((uint8_t)(0x01U >> x))
Definition at line 52 of file uvfr_utils.h.
deserializeBigE16
#define deserializeBigE16 (x, i) ((x[i]<<8)|(x[i+1]))
Definition at line 63 of file uvfr_utils.h.
deserializeBigE32
#define deserializeBigE32 (x, i) ((x[i]<<24)|(x[i+1]<<16)|(x[i+2]<<8)|(x[i+3]))
Definition at line 64 of file uvfr_utils.h.
deserializeSmallE16
#define deserializeSmallE16 (x, i) ((x[i])|(x[i+1]<<8))
Definition at line 61 of file uvfr_utils.h.
deserializeSmallE32
#define deserializeSmallE32 (x, i) ((x[i])|(x[i+1]<<8)|(x[i+2]<<16)|(x[i+3]<<24))
Definition at line 62 of file uvfr_utils.h.
endianSwap
#define endianSwap (x) endianSwap16(x)
Definition at line 56 of file uvfr_utils.h.
endianSwap16
#define endianSwap16 (x) (((x & 0x00FF)<<8) | ((x & 0xFF00)>>8))
Definition at line 58 of file uvfr_utils.h.
endianSwap32
#define endianSwap32 (x) (((x & 0x000000FF)<<16)|((x & 0x0000FF00)<<8)|((x & 0x00FF0000)>>8)|((x & 0xFF000000)>>16))
Definition at line 59 of file uvfr_utils.h.
endianSwap8
#define endianSwap8 (x) x
Definition at line 57 of file uvfr_utils.h.
false
#define false 0
Definition at line 72 of file uvfr_utils.h.
INIT_CHECK_PERIOD
#define INIT_CHECK_PERIOD 100
Definition at line 88 of file uvfr_utils.h.
MAX_INIT_TIME
#define MAX_INIT_TIME 2500
Definition at line 87 of file uvfr_utils.h.
serializeBigE16
#define serializeBigE16 (x, d, i) x[i+1]=d&0x00FF; x[i]=(d&0xFF00)>>8
Definition at line 68 of file uvfr_utils.h.
serializeBigE32
#define serializeBigE32 (x, d, i) x[i+3]=d&0x000000FF; x[i+2]=(d&0x0000FF00)>>8; x[i+1]=(d&0x00FF0000)>>16; x[i]=(d&0xFF000000)>>24
Definition at line 69 of file uvfr_utils.h.
serializeSmallE16
#define serializeSmallE16 (x, d, i) x[i]=d&0x00FF; x[i+1]=(d&0xFF00)>>8
Definition at line 66 of file uvfr_utils.h.
serializeSmallE32
#define serializeSmallE32 (x, d, i) x[i]=d&0x000000FF; x[i+1]=(d&0x0000FF00)>>8; x[i+2]=(d&0x00FF0000)>>16; x[i+3]=(d&0xFF000000)>>24
Definition at line 67 of file uvfr_utils.h.
true
#define true !false
Definition at line 73 of file uvfr_utils.h.
USE_OLED_DEBUG
#define USE_OLED_DEBUG 1
Definition at line 105 of file uvfr_utils.h.
UV_CAN1
#define UV_CAN1
Definition at line 101 of file uvfr_utils.h.
UV_CAN2
#define UV_CAN2
Definition at line 102 of file uvfr_utils.h.
UV_CAN_CHANNEL_MASK
#define UV_CAN_CHANNEL_MASK 0b00000110
Definition at line 205 of file uvfr_utils.h.
UV_CAN_EXTENDED_ID
#define UV_CAN_EXTENDED_ID 0x01
Definition at line 204 of file uvfr_utils.h.
UV_TASK_DORMANT_SVC
#define UV_TASK_DORMANT_SVC 0b00000011
Definition at line 228 of file uvfr_utils.h.
UV_TASK_LOG_MEM_USAGE
#define UV_TASK_LOG_MEM_USAGE 0b00001000
Definition at line 231 of file uvfr_utils.h.
UV_TASK_LOG_START_STOP_TIME
#define UV_TASK_LOG_START_STOP_TIME 0b00000100
Definition at line 230 of file uvfr_utils.h.
UV_TASK_MANAGER_MASK
#define UV_TASK_MANAGER_MASK 0b00000011
Definition at line 229 of file uvfr_utils.h.
UV_TASK_PERIODIC_SVC
#define UV_TASK_PERIODIC_SVC 0b00000010
Definition at line 227 of file uvfr_utils.h.
UV_TASK_SCD_IGNORE
#define UV_TASK_SCD_IGNORE 0b00010000
Definition at line 232 of file uvfr_utils.h.
UV_TASK_VEHICLE_APPLICATION
#define UV_TASK_VEHICLE_APPLICATION 0b00000001
Definition at line 226 of file uvfr_utils.h.
Typedef Documentation
access_control_info
typedef union access_control_info access_control_info
access_control_type
typedef enum access_control_t access_control_type
bool
typedef uint8_t bool
Definition at line 77 of file uvfr_utils.h.
p_status
typedef struct p_status p_status
task_management_data
typedef struct tm_data task_management_data
task_priority
typedef enum task_priority task_priority
uv_CAN_msg
typedef struct uv_CAN_msg uv_CAN_msg
uv_ext_device_id
typedef uint8_t uv_ext_device_id
Definition at line 81 of file uvfr_utils.h.
uv_init_struct
typedef struct uv_init_struct uv_init_struct
contains info relevant to initializing the vehicle
uv_init_task_args
typedef struct uv_init_task_args uv_init_task_args
Struct designed to act like the uv_task_info struct, but for the initialisation tasks. As a result it takes fewer arguments.
uv_init_task_response
typedef struct uv_init_task_response uv_init_task_response
Struct representing the response of one of the initialization tasks.
Is returned in the initialization queue, and is read by uvInit() to determine whether the initialization of the internal device has failed or succeeded.
uv_internal_params
typedef struct uv_internal_params uv_internal_params
Data used by the uvfr_utils library to do what it needs to do :)
This is a global variable that is initialized at some point at launch
uv_status
typedef enum uv_status_t uv_status
This is meant to be a return type from functions that indicates what is actually going on.
Use this as a return value for functions you want to know the success of. In general, any function you write must return something, as well as account for any possible errors that may have occurred.
uv_task_cmd
typedef enum uv_task_cmd_e uv_task_cmd
Definition at line 79 of file uvfr_utils.h.
uv_task_id
typedef uint8_t uv_task_id
Definition at line 78 of file uvfr_utils.h.
uv_task_info
typedef struct uv_task_info uv_task_info
This struct is designed to hold neccessary information about an RTOS task that will be managed by uvfr_state_engine.
task_id is an internal ID assigned to every task and is used by uvfr_utils. task_name is the name of the task. This must be less than 15 characters, and ended with a null terminator.
task_function is a pointer to the function we want the task to run task_priority is the priority of the task max_instances is the number of legal instances
task_state is an internal representation of what the task is up to. This is needed because the RTOS task may not actually exist. active_states dictates when the states are active
task_handle is an osThreadId created by FreeRTOS when it initializes the task. next exists because this shit needs to exist in a linked list, and my ass is too lazy to create a generic struct with it
cmd_data stores the command we really want this task to execute
uv_task_status
typedef enum uv_task_state_t uv_task_status
uv_timespan_ms
typedef uint32_t uv_timespan_ms
Definition at line 82 of file uvfr_utils.h.
Enumeration Type Documentation
access_control_t
enum access_control_t
Enumerator
UV_NONE
UV_DUMB_FLAG
UV_MUTEX
UV_BINARY_SEMAPHORE
UV_SEMAPHORE
Definition at line 173 of file uvfr_utils.h.
task_priority
enum task_priority
Enumerator
IDLE_TASK_PRIORITY
LOW_PRIORITY
BELOW_NORMAL
MEDIUM_PRIORITY
ABOVE_NORMAL
HIGH_PRIORITY
REALTIME_PRIORITY
Definition at line 130 of file uvfr_utils.h.
uv_driving_mode_t
enum uv_driving_mode_t
Enumerator
normal
accel
econ
limp
Definition at line 156 of file uvfr_utils.h.
uv_external_device
enum uv_external_device
ID for external devices, which allows us to know what's good with them.
Enumerator
MOTOR_CONTROLLER
BMS
IMD
PDU
Definition at line 166 of file uvfr_utils.h.
uv_status_t
enum uv_status_t
This is meant to be a return type from functions that indicates what is actually going on.
Use this as a return value for functions you want to know the success of. In general, any function you write must return something, as well as account for any possible errors that may have occurred.
Enumerator
UV_OK
UV_WARNING
UV_ERROR
UV_ABORTED
Definition at line 114 of file uvfr_utils.h.
uv_task_state_t
enum uv_task_state_t
Enumerator
UV_TASK_NOT_STARTED
UV_TASK_DELETED
UV_TASK_RUNNING
UV_TASK_SUSPENDED
Definition at line 123 of file uvfr_utils.h.
uv_vehicle_state_t
enum uv_vehicle_state_t
Type made to represent the state of the vehicle, and the location in the state machine The states are powers of two to make it easier to discern tasks that need to happen in multiple states
Enumerator
UV_INIT
UV_READY
PROGRAMMING
UV_DRIVING
UV_SUSPENDED
UV_LAUNCH_CONTROL
UV_ERROR_STATE
UV_BOOT
UV_HALT
Definition at line 143 of file uvfr_utils.h.
Function Documentation
__uvInitPanic()
void __uvInitPanic ()
Low Level Panic, that does not require the full UVFR utils functionality to be operational.
Attention
Calling _uvInitPanic() is irreversable and will cause the vehicle to hang itself. This is only to be used as a last resort to stop the vehicle from entering an invalid state.
Definition at line 300 of file uvfr_utils.c.
Referenced by uvInit(), uvInitStateEngine(), and uvSVCTaskManager().
uvInit()
void uvInit (void * arguments)
: Function that initializes all of the car's stuff.
This is an RTOS task, and it serves to setup all of the car's different functions. at this point in our execution, we have already initialized all of our favorite hardware peripherals using HAL. Now we get to configure our convoluted system of OS-level settings and state machines.
It executes the following functions, in order:
Load Vehicle Settings
Initialize and Start State Machine
Start Service Tasks, such as CAN, ADC, etc...
Initialize External Devices such as BMS, IMD, Motor Controller
Validate that these devices have actually booted up
Set vehicle state to UV_READY
Pretty important shit if you ask me.
First on the block is our settings. The uv_settings are a bit strange, in the following way. We will check if we have saved custom settings, or if these settings are the default or not. It will then perform a checksum on the settings, and validate them to ensure they are safe If it fails to validate the settings, it will attempt to return to factory default.
If it is unable to return even to factory default settings, then we are in HUGE trouble, and some catastrophic bug has occurred. If it fails to even start this, it will not be safe to drive We must therefore panic.
Next up we will attempt to initialize the state engine. If this fails, then we are in another case where we are genuinely unsafe to drive. This will create the prototypes for a bajillion tasks that will be started and stopped. Which tasks are currently running, depends on the whims of the state engine. Since the state engine is critical to our ability to handle errors and implausibilitys, we cannot proceed without a fully operational state engine.
Once the state machine is initialized we get to actually start the thing.
Once we have initialized the state engine, what we want to do is create the prototypes of all the tasks that will be running.
Now we are going to create a bunch of tasks that will initialize our car's external devices. The reason that these are RTOS tasks, is that it takes a buncha time to verify the existance of some devices. As a direct result, we can sorta just wait around and check that each task sends a message confirming that it has successfully executed. :) However, first we need to actually create a Queue for these tasks to use
  /
QueueHandle_t init_validation_queue = xQueueCreate(8,sizeof(uv_init_task_response));
if(init_validation_queue == NULL){
    __uvInitPanic();
}
The next big thing on our plate is checking the status of all external devices we need, and initializing them with appropriate parameters. These are split into tasks because it takes a bit of time, especially for devices that need to be configured via CANBus such as the motor controller. That is why it is split the way it is, to allow these to run somewhat concurrently
 */
BaseType_t retval;
//osThreadDef_t MC_init_thread = {"MC_init",MC_Startup,osPriorityNormal,128,0};
uv_init_task_args* MC_init_args = uvMalloc(sizeof(uv_init_task_args));
MC_init_args->init_info_queue = init_validation_queue;
MC_init_args->specific_args = &(current_vehicle_settings->motor_controller_settings);
//MC_init_args->meta_task_handle = osThreadCreate(&MC_init_thread,MC_init_args);
//vTaskResume(MC_init_args->meta_task_handle);
retval = xTaskCreate(MC_Startup,"MC_init",128,MC_init_args,osPriorityAboveNormal,&(MC_init_args->meta_task_handle));
if(retval != pdPASS){
    //FUCK
    error_msg = "bruh";
}
This thread is for initializing the BMS
 */
//osThreadDef_t BMS_init_thread = {"BMS_init",BMS_Init,osPriorityNormal,128,0};
uv_init_task_args* BMS_init_args = uvMalloc(sizeof(uv_init_task_args));
BMS_init_args->init_info_queue = init_validation_queue;
BMS_init_args->specific_args = &(current_vehicle_settings->bms_settings);
//BMS_init_args->meta_task_handle = osThreadCreate(&BMS_init_thread,BMS_init_args);
retval = xTaskCreate(BMS_Init,"BMS_init",128,BMS_init_args,osPriorityAboveNormal,&(BMS_init_args->meta_task_handle));
if(retval != pdPASS){
    //FUCK
    error_msg = "bruh";
}
This variable is a tracker that tracks which devices have successfully initialized
 */
uv_init_task_args* IMD_init_args = uvMalloc(sizeof(uv_init_task_args));
IMD_init_args->init_info_queue = init_validation_queue;
IMD_init_args->specific_args = &(current_vehicle_settings->imd_settings);
retval = xTaskCreate(initIMD,"BMS_init",128,IMD_init_args,osPriorityAboveNormal,&(IMD_init_args->meta_task_handle));
if(retval != pdPASS){
        //FUCK
    error_msg = "bruh";
}
uv_init_task_args* PDU_init_args = uvMalloc(sizeof(uv_init_task_args));
PDU_init_args->init_info_queue = init_validation_queue;
PDU_init_args->specific_args = &(current_vehicle_settings->imd_settings);
retval = xTaskCreate(initPDU,"PDU_init",128,PDU_init_args,osPriorityAboveNormal,&(PDU_init_args->meta_task_handle)); //pass in the right settings, dumdum
if(retval != pdPASS){
        //FUCK
    error_msg = "bruh";
}
uint16_t ext_devices_status = 0x000F; //Tracks which devices are currently setup
Wait for all the spawned in tasks to do their thing. This should not take that long, but we wanna be sure that everything is chill If we are say, missing a BMS, then it will not allow you to proceed past the initialisation step This is handled by a message buffer, that takes inputs from all of the tasks
We allocate space for a response from the initialization.
Clean up, clean up, everybody clean up, clean up, clean up, everybody do your share! The following code cleans up all the threads that were running, and free up used memory
Definition at line 37 of file uvfr_utils.c.
References __uvInitPanic(), BMS_Init(), uv_vehicle_settings::bms_settings, changeVehicleState(), current_vehicle_settings, uv_init_task_response::device, uv_init_task_response::errmsg, handleCANbusError(), hcan2, uv_vehicle_settings::imd_settings, INIT_CHECK_PERIOD, uv_init_task_args::init_info_queue, init_task_handle, initIMD(), initPDU(), MAX_INIT_TIME, MC_Startup(), uv_init_task_args::meta_task_handle, uv_vehicle_settings::motor_controller_settings, uv_init_task_response::nchar, uv_init_task_args::specific_args, uv_init_task_response::status, TxData, TxHeader, TxMailbox, UV_OK, UV_READY, uvFree(), uvInitStateEngine(), uvPanic(), uvSettingsInit(), and uvStartStateMachine().
Referenced by MX_FREERTOS_Init().
uvIsPTRValid()
uv_status uvIsPTRValid (void * ptr)
function that checks to make sure a pointer points to a place it is allowed to point to
The primary motivation for this is to avoid trying to dereference a pointer that doesnt exist, and triggering the HardFaultHandler(). That is never a fun time. This allows us to exit gracefully instead of getting stuck in an IRQ handler
Exiting gracefully can be pretty neat sometimes.
Definition at line 430 of file uvfr_utils.c.
References UV_ERROR, UV_OK, and UV_WARNING.
Referenced by __uvFreeCritSection(), __uvFreeOS(), and __uvMallocOS().
Variable Documentation
global_context
uv_internal_params global_context